<?php

use Illuminate\Database\Seeder;
use App\District;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            'Carmen',
            'Merced',
            'Hospital',
            'Catedral',
            'Zapote',
            'San Francisco de Dos Ríos',
            'Uruca',
            'Mata Redonda',
            'Pavas',
            'Hatillo',
            'San Sebastián',
            'Escazú',
            'San Antonio',
            'San Rafael',
            'Desamparados',
            'San Miguel',
            'San Juan de Dios',
            'San Rafael Arriba',
            'San Antonio',
            'Frailes',
            'Patarrá',
            'San Cristóbal',
            'Rosario',
            'Damas',
            'San Rafael Abajo',
            'Gravilias',
            'Los Guido',
            'Santiago',
            'Mercedes Sur',
            'Barbacoas',
            'Grifo Alto',
            'San Rafael',
            'Candelaria',
            'Desamparaditos',
            'San Antonio',
            'Chires',
            'San Marcos',
            'San Lorenzo',
            'San Carlos',
            'Aserrí',
            'Tarbaca o Praga',
            'Vuelta de Jorco',
            'San Gabriel',
            'La Legua',
            'Monterrey',
            'Salitrillos',
            'Colón',
            'Guayabo',
            'Tabarcia',
            'Piedras Negras',
            'Picagres',
            'Guadalupe',
            'San Francisco',
            'Calle Blancos',
            'Mata de Plátano',
            'Ipís',
            'Rancho Redondo',
            'Purral',
            'Santa Ana',
            'Salitral',
            'Pozos o Concepción',
            'Uruca o San Joaquín',
            'Piedades',
            'Brasil',
            'Alajuelita',
            'San Josecito',
            'San Antonio',
            'Concepción',
            'San Felipe',
            'San Isidro',
            'San Rafael',
            'Dulce Nombre de Jesús',
            'Patalillo',
            'Cascajal',
            'San Ignacio',
            'Guaitil',
            'Palmichal',
            'Cangrejal',
            'Sabanillas',
            'San Juan',
            'Cinco Esquinas',
            'Anselmo Llorente',
            'León XIII',
            'Colima',
            'San Vicente',
            'San Jerónimo',
            'Trinidad',
            'San Pedro',
            'Sabanilla',
            'Mercedes o Betania',
            'San Rafael',
            'San Pablo',
            'San Pedro',
            'San Juan de Mata',
            'San Luis',
            'Cárara',
            'Santa María',
            'Jardín',
            'Copey',
            'Curridabat',
            'Granadilla',
            'Sánchez',
            'Tirrases',
            'San Isidro de el General',
            'General',
            'Daniel Flores',
            'Rivas',
            'San Pedro',
            'Platanares',
            'Pejibaye',
            'Cajón',
            'Barú',
            'Río Nuevo',
            'Páramo',
            'San Pablo',
            'San Andrés',
            'Llano Bonito',
            'San Isidro',
            'Santa Cruz',
            'San Antonio',
            'Alajuela',
            'San José',
            'Carrizal',
            'San Antonio',
            'Guácima',
            'San Isidro',
            'Sabanilla',
            'San Rafael',
            'Río Segundo',
            'Desamparados',
            'Turrucares',
            'Tambor',
            'La Garita',
            'Sarapiquí',
            'San Ramón',
            'Santiago',
            'San Juan',
            'Piedades Norte',
            'Piedades Sur',
            'San Rafael',
            'San Isidro',
            'Angeles',
            'Alfaro',
            'Volio',
            'Concepción',
            'Zapotal',
            'San Isidro de Peñas Blancas',
            'Grecia',
            'San Isidro',
            'San José',
            'San Roque',
            'Tacares',
            'Río Cuarto',
            'Puente Piedra',
            'Bolívar',
            'San Mateo',
            'Desmonte',
            'Jesús María',
            'Atenas',
            'Jesús',
            'Mercedes',
            'San Isidro',
            'Concepción',
            'San José',
        ];
      for ($i = 0; $i < count($names); $i++) {
            District::create ([
                'name' => $names[$i],
                'id_canton' => rand(1,25),
            ]);
        }  
    }
}
