<?php

use Illuminate\Database\Seeder;
use App\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Distritos = array(
            array('idDistrito' => '10101','idCanton' => '101','nombreDistrito' => 'CARMEN'),
            array('idDistrito' => '10102','idCanton' => '101','nombreDistrito' => 'MERCED'),
            array('idDistrito' => '10103','idCanton' => '101','nombreDistrito' => 'HOSPITAL'),
            array('idDistrito' => '10104','idCanton' => '101','nombreDistrito' => 'CATEDRAL'),
            array('idDistrito' => '10105','idCanton' => '101','nombreDistrito' => 'ZAPOTE'),
            array('idDistrito' => '10106','idCanton' => '101','nombreDistrito' => 'SAN FRANCISCO DE DOS RÍOS'),
            array('idDistrito' => '10107','idCanton' => '101','nombreDistrito' => 'URUCA'),
            array('idDistrito' => '10108','idCanton' => '101','nombreDistrito' => 'MATA REDONDA'),
            array('idDistrito' => '10109','idCanton' => '101','nombreDistrito' => 'PAVAS'),
            array('idDistrito' => '10110','idCanton' => '101','nombreDistrito' => 'HATILLO'),
            array('idDistrito' => '10111','idCanton' => '101','nombreDistrito' => 'SAN SEBASTIÁN'),
            array('idDistrito' => '10201','idCanton' => '102','nombreDistrito' => 'ESCAZÚ'),
            array('idDistrito' => '10202','idCanton' => '102','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '10203','idCanton' => '102','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '10301','idCanton' => '103','nombreDistrito' => 'DESAMPARADOS'),
            array('idDistrito' => '10302','idCanton' => '103','nombreDistrito' => 'SAN MIGUEL'),
            array('idDistrito' => '10303','idCanton' => '103','nombreDistrito' => 'SAN JUAN DE DIOS'),
            array('idDistrito' => '10304','idCanton' => '103','nombreDistrito' => 'SAN RAFAEL ARRIBA'),
            array('idDistrito' => '10305','idCanton' => '103','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '10306','idCanton' => '103','nombreDistrito' => 'FRAILES'),
            array('idDistrito' => '10307','idCanton' => '103','nombreDistrito' => 'PATARRÁ'),
            array('idDistrito' => '10308','idCanton' => '103','nombreDistrito' => 'SAN CRISTÓBAL'),
            array('idDistrito' => '10309','idCanton' => '103','nombreDistrito' => 'ROSARIO'),
            array('idDistrito' => '10310','idCanton' => '103','nombreDistrito' => 'DAMAS'),
            array('idDistrito' => '10311','idCanton' => '103','nombreDistrito' => 'SAN RAFAEL ABAJO'),
            array('idDistrito' => '10312','idCanton' => '103','nombreDistrito' => 'GRAVILIAS'),
            array('idDistrito' => '10313','idCanton' => '103','nombreDistrito' => 'LOS GUIDO'),
            array('idDistrito' => '10401','idCanton' => '104','nombreDistrito' => 'SANTIAGO'),
            array('idDistrito' => '10402','idCanton' => '104','nombreDistrito' => 'MERCEDES SUR'),
            array('idDistrito' => '10403','idCanton' => '104','nombreDistrito' => 'BARBACOAS'),
            array('idDistrito' => '10404','idCanton' => '104','nombreDistrito' => 'GRIFO ALTO'),
            array('idDistrito' => '10405','idCanton' => '104','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '10406','idCanton' => '104','nombreDistrito' => 'CANDELARIA'),
            array('idDistrito' => '10407','idCanton' => '104','nombreDistrito' => 'DESAMPARADITOS'),
            array('idDistrito' => '10408','idCanton' => '104','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '10409','idCanton' => '104','nombreDistrito' => 'CHIRES'),
            array('idDistrito' => '10501','idCanton' => '105','nombreDistrito' => 'SAN MARCOS'),
            array('idDistrito' => '10502','idCanton' => '105','nombreDistrito' => 'SAN LORENZO'),
            array('idDistrito' => '10503','idCanton' => '105','nombreDistrito' => 'SAN CARLOS'),
            array('idDistrito' => '10601','idCanton' => '106','nombreDistrito' => 'ASERRÍ'),
            array('idDistrito' => '10602','idCanton' => '106','nombreDistrito' => 'TARBACA O PRAGA'),
            array('idDistrito' => '10603','idCanton' => '106','nombreDistrito' => 'VUELTA DE JORCO'),
            array('idDistrito' => '10604','idCanton' => '106','nombreDistrito' => 'SAN GABRIEL'),
            array('idDistrito' => '10605','idCanton' => '106','nombreDistrito' => 'LA LEGUA'),
            array('idDistrito' => '10606','idCanton' => '106','nombreDistrito' => 'MONTERREY'),
            array('idDistrito' => '10607','idCanton' => '106','nombreDistrito' => 'SALITRILLOS'),
            array('idDistrito' => '10701','idCanton' => '107','nombreDistrito' => 'COLÓN'),
            array('idDistrito' => '10702','idCanton' => '107','nombreDistrito' => 'GUAYABO'),
            array('idDistrito' => '10703','idCanton' => '107','nombreDistrito' => 'TABARCIA'),
            array('idDistrito' => '10704','idCanton' => '107','nombreDistrito' => 'PIEDRAS NEGRAS'),
            array('idDistrito' => '10705','idCanton' => '107','nombreDistrito' => 'PICAGRES'),
            array('idDistrito' => '10801','idCanton' => '108','nombreDistrito' => 'GUADALUPE'),
            array('idDistrito' => '10802','idCanton' => '108','nombreDistrito' => 'SAN FRANCISCO'),
            array('idDistrito' => '10803','idCanton' => '108','nombreDistrito' => 'CALLE BLANCOS'),
            array('idDistrito' => '10804','idCanton' => '108','nombreDistrito' => 'MATA DE PLÁTANO'),
            array('idDistrito' => '10805','idCanton' => '108','nombreDistrito' => 'IPÍS'),
            array('idDistrito' => '10806','idCanton' => '108','nombreDistrito' => 'RANCHO REDONDO'),
            array('idDistrito' => '10807','idCanton' => '108','nombreDistrito' => 'PURRAL'),
            array('idDistrito' => '10901','idCanton' => '109','nombreDistrito' => 'SANTA ANA'),
            array('idDistrito' => '10902','idCanton' => '109','nombreDistrito' => 'SALITRAL'),
            array('idDistrito' => '10903','idCanton' => '109','nombreDistrito' => 'POZOS O CONCEPCIÓN'),
            array('idDistrito' => '10904','idCanton' => '109','nombreDistrito' => 'URUCA O SAN JOAQUÍN'),
            array('idDistrito' => '10905','idCanton' => '109','nombreDistrito' => 'PIEDADES'),
            array('idDistrito' => '10906','idCanton' => '109','nombreDistrito' => 'BRASIL'),
            array('idDistrito' => '11001','idCanton' => '110','nombreDistrito' => 'ALAJUELITA'),
            array('idDistrito' => '11002','idCanton' => '110','nombreDistrito' => 'SAN JOSECITO'),
            array('idDistrito' => '11003','idCanton' => '110','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '11004','idCanton' => '110','nombreDistrito' => 'CONCEPCIÓN'),
            array('idDistrito' => '11005','idCanton' => '110','nombreDistrito' => 'SAN FELIPE'),
            array('idDistrito' => '11101','idCanton' => '111','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '11102','idCanton' => '111','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '11103','idCanton' => '111','nombreDistrito' => 'DULCE NOMBRE DE JESÚS'),
            array('idDistrito' => '11104','idCanton' => '111','nombreDistrito' => 'PATALILLO'),
            array('idDistrito' => '11105','idCanton' => '111','nombreDistrito' => 'CASCAJAL'),
            array('idDistrito' => '11201','idCanton' => '112','nombreDistrito' => 'SAN IGNACIO'),
            array('idDistrito' => '11202','idCanton' => '112','nombreDistrito' => 'GUAITIL'),
            array('idDistrito' => '11203','idCanton' => '112','nombreDistrito' => 'PALMICHAL'),
            array('idDistrito' => '11204','idCanton' => '112','nombreDistrito' => 'CANGREJAL'),
            array('idDistrito' => '11205','idCanton' => '112','nombreDistrito' => 'SABANILLAS'),
            array('idDistrito' => '11301','idCanton' => '113','nombreDistrito' => 'SAN JUAN'),
            array('idDistrito' => '11302','idCanton' => '113','nombreDistrito' => 'CINCO ESQUINAS'),
            array('idDistrito' => '11303','idCanton' => '113','nombreDistrito' => 'ANSELMO LLORENTE'),
            array('idDistrito' => '11304','idCanton' => '113','nombreDistrito' => 'LEÓN XIII'),
            array('idDistrito' => '11305','idCanton' => '113','nombreDistrito' => 'COLIMA'),
            array('idDistrito' => '11401','idCanton' => '114','nombreDistrito' => 'SAN VICENTE'),
            array('idDistrito' => '11402','idCanton' => '114','nombreDistrito' => 'SAN JERÓNIMO'),
            array('idDistrito' => '11403','idCanton' => '114','nombreDistrito' => 'TRINIDAD'),
            array('idDistrito' => '11501','idCanton' => '115','nombreDistrito' => 'SAN PEDRO'),
            array('idDistrito' => '11502','idCanton' => '115','nombreDistrito' => 'SABANILLA'),
            array('idDistrito' => '11503','idCanton' => '115','nombreDistrito' => 'MERCEDES O BETANIA'),
            array('idDistrito' => '11504','idCanton' => '115','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '11601','idCanton' => '116','nombreDistrito' => 'SAN PABLO'),
            array('idDistrito' => '11602','idCanton' => '116','nombreDistrito' => 'SAN PEDRO'),
            array('idDistrito' => '11603','idCanton' => '116','nombreDistrito' => 'SAN JUAN DE MATA'),
            array('idDistrito' => '11604','idCanton' => '116','nombreDistrito' => 'SAN LUIS'),
            array('idDistrito' => '11605','idCanton' => '116','nombreDistrito' => 'CÁRARA'),
            array('idDistrito' => '11701','idCanton' => '117','nombreDistrito' => 'SANTA MARÍA'),
            array('idDistrito' => '11702','idCanton' => '117','nombreDistrito' => 'JARDÍN'),
            array('idDistrito' => '11703','idCanton' => '117','nombreDistrito' => 'COPEY'),
            array('idDistrito' => '11801','idCanton' => '118','nombreDistrito' => 'CURRIDABAT'),
            array('idDistrito' => '11802','idCanton' => '118','nombreDistrito' => 'GRANADILLA'),
            array('idDistrito' => '11803','idCanton' => '118','nombreDistrito' => 'SÁNCHEZ'),
            array('idDistrito' => '11804','idCanton' => '118','nombreDistrito' => 'TIRRASES'),
            array('idDistrito' => '11901','idCanton' => '119','nombreDistrito' => 'SAN ISIDRO DE EL GENERAL'),
            array('idDistrito' => '11902','idCanton' => '119','nombreDistrito' => 'GENERAL'),
            array('idDistrito' => '11903','idCanton' => '119','nombreDistrito' => 'DANIEL FLORES'),
            array('idDistrito' => '11904','idCanton' => '119','nombreDistrito' => 'RIVAS'),
            array('idDistrito' => '11905','idCanton' => '119','nombreDistrito' => 'SAN PEDRO'),
            array('idDistrito' => '11906','idCanton' => '119','nombreDistrito' => 'PLATANARES'),
            array('idDistrito' => '11907','idCanton' => '119','nombreDistrito' => 'PEJIBAYE'),
            array('idDistrito' => '11908','idCanton' => '119','nombreDistrito' => 'CAJÓN'),
            array('idDistrito' => '11909','idCanton' => '119','nombreDistrito' => 'BARÚ'),
            array('idDistrito' => '11910','idCanton' => '119','nombreDistrito' => 'RÍO NUEVO'),
            array('idDistrito' => '11911','idCanton' => '119','nombreDistrito' => 'PÁRAMO'),
            array('idDistrito' => '12001','idCanton' => '120','nombreDistrito' => 'SAN PABLO'),
            array('idDistrito' => '12002','idCanton' => '120','nombreDistrito' => 'SAN ANDRÉS'),
            array('idDistrito' => '12003','idCanton' => '120','nombreDistrito' => 'LLANO BONITO'),
            array('idDistrito' => '12004','idCanton' => '120','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '12005','idCanton' => '120','nombreDistrito' => 'SANTA CRUZ'),
            array('idDistrito' => '12006','idCanton' => '120','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '20101','idCanton' => '201','nombreDistrito' => 'ALAJUELA'),
            array('idDistrito' => '20102','idCanton' => '201','nombreDistrito' => 'SAN JOSÉ'),
            array('idDistrito' => '20103','idCanton' => '201','nombreDistrito' => 'CARRIZAL'),
            array('idDistrito' => '20104','idCanton' => '201','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '20105','idCanton' => '201','nombreDistrito' => 'GUÁCIMA'),
            array('idDistrito' => '20106','idCanton' => '201','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '20107','idCanton' => '201','nombreDistrito' => 'SABANILLA'),
            array('idDistrito' => '20108','idCanton' => '201','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '20109','idCanton' => '201','nombreDistrito' => 'RÍO SEGUNDO'),
            array('idDistrito' => '20110','idCanton' => '201','nombreDistrito' => 'DESAMPARADOS'),
            array('idDistrito' => '20111','idCanton' => '201','nombreDistrito' => 'TURRUCARES'),
            array('idDistrito' => '20112','idCanton' => '201','nombreDistrito' => 'TAMBOR'),
            array('idDistrito' => '20113','idCanton' => '201','nombreDistrito' => 'LA GARITA'),
            array('idDistrito' => '20114','idCanton' => '201','nombreDistrito' => 'SARAPIQUÍ'),
            array('idDistrito' => '20201','idCanton' => '202','nombreDistrito' => 'SAN RAMÓN'),
            array('idDistrito' => '20202','idCanton' => '202','nombreDistrito' => 'SANTIAGO'),
            array('idDistrito' => '20203','idCanton' => '202','nombreDistrito' => 'SAN JUAN'),
            array('idDistrito' => '20204','idCanton' => '202','nombreDistrito' => 'PIEDADES NORTE'),
            array('idDistrito' => '20205','idCanton' => '202','nombreDistrito' => 'PIEDADES SUR'),
            array('idDistrito' => '20206','idCanton' => '202','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '20207','idCanton' => '202','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '20208','idCanton' => '202','nombreDistrito' => 'ANGELES'),
            array('idDistrito' => '20209','idCanton' => '202','nombreDistrito' => 'ALFARO'),
            array('idDistrito' => '20210','idCanton' => '202','nombreDistrito' => 'VOLIO'),
            array('idDistrito' => '20211','idCanton' => '202','nombreDistrito' => 'CONCEPCIÓN'),
            array('idDistrito' => '20212','idCanton' => '202','nombreDistrito' => 'ZAPOTAL'),
            array('idDistrito' => '20213','idCanton' => '202','nombreDistrito' => 'SAN ISIDRO DE PEÑAS BLANCAS'),
            array('idDistrito' => '20301','idCanton' => '203','nombreDistrito' => 'GRECIA'),
            array('idDistrito' => '20302','idCanton' => '203','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '20303','idCanton' => '203','nombreDistrito' => 'SAN JOSÉ'),
            array('idDistrito' => '20304','idCanton' => '203','nombreDistrito' => 'SAN ROQUE'),
            array('idDistrito' => '20305','idCanton' => '203','nombreDistrito' => 'TACARES'),
            array('idDistrito' => '20306','idCanton' => '203','nombreDistrito' => 'RÍO CUARTO'),
            array('idDistrito' => '20307','idCanton' => '203','nombreDistrito' => 'PUENTE PIEDRA'),
            array('idDistrito' => '20308','idCanton' => '203','nombreDistrito' => 'BOLÍVAR'),
            array('idDistrito' => '20401','idCanton' => '204','nombreDistrito' => 'SAN MATEO'),
            array('idDistrito' => '20402','idCanton' => '204','nombreDistrito' => 'DESMONTE'),
            array('idDistrito' => '20403','idCanton' => '204','nombreDistrito' => 'JESÚS MARÍA'),
            array('idDistrito' => '20501','idCanton' => '205','nombreDistrito' => 'ATENAS'),
            array('idDistrito' => '20502','idCanton' => '205','nombreDistrito' => 'JESÚS'),
            array('idDistrito' => '20503','idCanton' => '205','nombreDistrito' => 'MERCEDES'),
            array('idDistrito' => '20504','idCanton' => '205','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '20505','idCanton' => '205','nombreDistrito' => 'CONCEPCIÓN'),
            array('idDistrito' => '20506','idCanton' => '205','nombreDistrito' => 'SAN JOSÉ'),
            array('idDistrito' => '20507','idCanton' => '205','nombreDistrito' => 'SANTA EULALIA'),
            array('idDistrito' => '20508','idCanton' => '205','nombreDistrito' => 'ESCOBAL'),
            array('idDistrito' => '20601','idCanton' => '206','nombreDistrito' => 'NARANJO'),
            array('idDistrito' => '20602','idCanton' => '206','nombreDistrito' => 'SAN MIGUEL'),
            array('idDistrito' => '20603','idCanton' => '206','nombreDistrito' => 'SAN JOSÉ'),
            array('idDistrito' => '20604','idCanton' => '206','nombreDistrito' => 'CIRRÍ SUR'),
            array('idDistrito' => '20605','idCanton' => '206','nombreDistrito' => 'SAN JERÓNIMO'),
            array('idDistrito' => '20606','idCanton' => '206','nombreDistrito' => 'SAN JUAN'),
            array('idDistrito' => '20607','idCanton' => '206','nombreDistrito' => 'ROSARIO'),
            array('idDistrito' => '20701','idCanton' => '207','nombreDistrito' => 'PALMARES'),
            array('idDistrito' => '20702','idCanton' => '207','nombreDistrito' => 'ZARAGOZA'),
            array('idDistrito' => '20703','idCanton' => '207','nombreDistrito' => 'BUENOS AIRES'),
            array('idDistrito' => '20704','idCanton' => '207','nombreDistrito' => 'SANTIAGO'),
            array('idDistrito' => '20705','idCanton' => '207','nombreDistrito' => 'CANDELARIA'),
            array('idDistrito' => '20706','idCanton' => '207','nombreDistrito' => 'ESQUIPULAS'),
            array('idDistrito' => '20707','idCanton' => '207','nombreDistrito' => 'LA GRANJA'),
            array('idDistrito' => '20801','idCanton' => '208','nombreDistrito' => 'SAN PEDRO'),
            array('idDistrito' => '20802','idCanton' => '208','nombreDistrito' => 'SAN JUAN'),
            array('idDistrito' => '20803','idCanton' => '208','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '20804','idCanton' => '208','nombreDistrito' => 'CARRILLOS'),
            array('idDistrito' => '20805','idCanton' => '208','nombreDistrito' => 'SABANA REDONDA'),
            array('idDistrito' => '20901','idCanton' => '209','nombreDistrito' => 'OROTINA'),
            array('idDistrito' => '20902','idCanton' => '209','nombreDistrito' => 'MASTATE'),
            array('idDistrito' => '20903','idCanton' => '209','nombreDistrito' => 'HACIENDA VIEJA'),
            array('idDistrito' => '20904','idCanton' => '209','nombreDistrito' => 'COYOLAR'),
            array('idDistrito' => '20905','idCanton' => '209','nombreDistrito' => 'CEIBA'),
            array('idDistrito' => '21001','idCanton' => '210','nombreDistrito' => 'QUESADA'),
            array('idDistrito' => '21002','idCanton' => '210','nombreDistrito' => 'FLORENCIA'),
            array('idDistrito' => '21003','idCanton' => '210','nombreDistrito' => 'BUENAVISTA'),
            array('idDistrito' => '21004','idCanton' => '210','nombreDistrito' => 'AGUAS ZARCAS'),
            array('idDistrito' => '21005','idCanton' => '210','nombreDistrito' => 'VENECIA'),
            array('idDistrito' => '21006','idCanton' => '210','nombreDistrito' => 'PITAL'),
            array('idDistrito' => '21007','idCanton' => '210','nombreDistrito' => 'FORTUNA'),
            array('idDistrito' => '21008','idCanton' => '210','nombreDistrito' => 'TIGRA'),
            array('idDistrito' => '21009','idCanton' => '210','nombreDistrito' => 'PALMERA'),
            array('idDistrito' => '21010','idCanton' => '210','nombreDistrito' => 'VENADO'),
            array('idDistrito' => '21011','idCanton' => '210','nombreDistrito' => 'CUTRIS'),
            array('idDistrito' => '21012','idCanton' => '210','nombreDistrito' => 'MONTERREY'),
            array('idDistrito' => '21013','idCanton' => '210','nombreDistrito' => 'POCOSOL'),
            array('idDistrito' => '21101','idCanton' => '211','nombreDistrito' => 'ZARCERO'),
            array('idDistrito' => '21102','idCanton' => '211','nombreDistrito' => 'LAGUNA'),
            array('idDistrito' => '21103','idCanton' => '211','nombreDistrito' => 'TAPEZCO'),
            array('idDistrito' => '21104','idCanton' => '211','nombreDistrito' => 'GUADALUPE'),
            array('idDistrito' => '21105','idCanton' => '211','nombreDistrito' => 'PALMIRA'),
            array('idDistrito' => '21106','idCanton' => '211','nombreDistrito' => 'ZAPOTE'),
            array('idDistrito' => '21107','idCanton' => '211','nombreDistrito' => 'LAS BRISAS'),
            array('idDistrito' => '21201','idCanton' => '212','nombreDistrito' => 'SARCHÍ NORTE'),
            array('idDistrito' => '21202','idCanton' => '212','nombreDistrito' => 'SARCHÍ SUR'),
            array('idDistrito' => '21203','idCanton' => '212','nombreDistrito' => 'TORO AMARILLO'),
            array('idDistrito' => '21204','idCanton' => '212','nombreDistrito' => 'SAN PEDRO'),
            array('idDistrito' => '21205','idCanton' => '212','nombreDistrito' => 'RODRÍGUEZ'),
            array('idDistrito' => '21301','idCanton' => '213','nombreDistrito' => 'UPALA'),
            array('idDistrito' => '21302','idCanton' => '213','nombreDistrito' => 'AGUAS CLARAS'),
            array('idDistrito' => '21303','idCanton' => '213','nombreDistrito' => 'SAN JOSÉ O PIZOTE'),
            array('idDistrito' => '21304','idCanton' => '213','nombreDistrito' => 'BIJAGUA'),
            array('idDistrito' => '21305','idCanton' => '213','nombreDistrito' => 'DELICIAS'),
            array('idDistrito' => '21306','idCanton' => '213','nombreDistrito' => 'DOS RÍOS'),
            array('idDistrito' => '21307','idCanton' => '213','nombreDistrito' => 'YOLILLAL'),
            array('idDistrito' => '21401','idCanton' => '214','nombreDistrito' => 'LOS CHILES'),
            array('idDistrito' => '21402','idCanton' => '214','nombreDistrito' => 'CAÑO NEGRO'),
            array('idDistrito' => '21403','idCanton' => '214','nombreDistrito' => 'AMPARO'),
            array('idDistrito' => '21404','idCanton' => '214','nombreDistrito' => 'SAN JORGE'),
            array('idDistrito' => '21501','idCanton' => '215','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '21502','idCanton' => '215','nombreDistrito' => 'BUENAVISTA'),
            array('idDistrito' => '21503','idCanton' => '215','nombreDistrito' => 'COTE'),
            array('idDistrito' => '30101','idCanton' => '301','nombreDistrito' => 'ORIENTAL'),
            array('idDistrito' => '30102','idCanton' => '301','nombreDistrito' => 'OCCIDENTAL'),
            array('idDistrito' => '30103','idCanton' => '301','nombreDistrito' => 'CARMEN'),
            array('idDistrito' => '30104','idCanton' => '301','nombreDistrito' => 'SAN NICOLÁS'),
            array('idDistrito' => '30105','idCanton' => '301','nombreDistrito' => 'AGUACALIENTE O SAN FRANCISCO'),
            array('idDistrito' => '30106','idCanton' => '301','nombreDistrito' => 'GUADALUPE O ARENILLA'),
            array('idDistrito' => '30107','idCanton' => '301','nombreDistrito' => 'CORRALILLO'),
            array('idDistrito' => '30108','idCanton' => '301','nombreDistrito' => 'TIERRA BLANCA'),
            array('idDistrito' => '30109','idCanton' => '301','nombreDistrito' => 'DULCE NOMBRE'),
            array('idDistrito' => '30110','idCanton' => '301','nombreDistrito' => 'LLANO GRANDE'),
            array('idDistrito' => '30111','idCanton' => '301','nombreDistrito' => 'QUEBRADILLA'),
            array('idDistrito' => '30201','idCanton' => '302','nombreDistrito' => 'PARAÍSO'),
            array('idDistrito' => '30202','idCanton' => '302','nombreDistrito' => 'SANTIAGO'),
            array('idDistrito' => '30203','idCanton' => '302','nombreDistrito' => 'OROSI'),
            array('idDistrito' => '30204','idCanton' => '302','nombreDistrito' => 'CACHÍ'),
            array('idDistrito' => '30205','idCanton' => '302','nombreDistrito' => 'LOS LLANOS DE SANTA LUCÍA'),
            array('idDistrito' => '30301','idCanton' => '303','nombreDistrito' => 'TRES RÍOS'),
            array('idDistrito' => '30302','idCanton' => '303','nombreDistrito' => 'SAN DIEGO'),
            array('idDistrito' => '30303','idCanton' => '303','nombreDistrito' => 'SAN JUAN'),
            array('idDistrito' => '30304','idCanton' => '303','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '30305','idCanton' => '303','nombreDistrito' => 'CONCEPCIÓN'),
            array('idDistrito' => '30306','idCanton' => '303','nombreDistrito' => 'DULCE NOMBRE'),
            array('idDistrito' => '30307','idCanton' => '303','nombreDistrito' => 'SAN RAMÓN'),
            array('idDistrito' => '30308','idCanton' => '303','nombreDistrito' => 'RÍO AZUL'),
            array('idDistrito' => '30401','idCanton' => '304','nombreDistrito' => 'JUAN VIÑAS'),
            array('idDistrito' => '30402','idCanton' => '304','nombreDistrito' => 'TUCURRIQUE'),
            array('idDistrito' => '30403','idCanton' => '304','nombreDistrito' => 'PEJIBAYE'),
            array('idDistrito' => '30501','idCanton' => '305','nombreDistrito' => 'TURRIALBA'),
            array('idDistrito' => '30502','idCanton' => '305','nombreDistrito' => 'LA SUIZA'),
            array('idDistrito' => '30503','idCanton' => '305','nombreDistrito' => 'PERALTA'),
            array('idDistrito' => '30504','idCanton' => '305','nombreDistrito' => 'SANTA CRUZ'),
            array('idDistrito' => '30505','idCanton' => '305','nombreDistrito' => 'SANTA TERESITA'),
            array('idDistrito' => '30506','idCanton' => '305','nombreDistrito' => 'PAVONES'),
            array('idDistrito' => '30507','idCanton' => '305','nombreDistrito' => 'TUIS'),
            array('idDistrito' => '30508','idCanton' => '305','nombreDistrito' => 'TAYUTIC'),
            array('idDistrito' => '30509','idCanton' => '305','nombreDistrito' => 'SANTA ROSA'),
            array('idDistrito' => '30510','idCanton' => '305','nombreDistrito' => 'TRES EQUIS'),
            array('idDistrito' => '30511','idCanton' => '305','nombreDistrito' => 'LA ISABEL'),
            array('idDistrito' => '30512','idCanton' => '305','nombreDistrito' => 'CHIRRIPÓ'),
            array('idDistrito' => '30601','idCanton' => '306','nombreDistrito' => 'PACAYAS'),
            array('idDistrito' => '30602','idCanton' => '306','nombreDistrito' => 'CERVANTES'),
            array('idDistrito' => '30603','idCanton' => '306','nombreDistrito' => 'CAPELLADES'),
            array('idDistrito' => '30701','idCanton' => '307','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '30702','idCanton' => '307','nombreDistrito' => 'COT'),
            array('idDistrito' => '30703','idCanton' => '307','nombreDistrito' => 'POTRERO CERRADO'),
            array('idDistrito' => '30704','idCanton' => '307','nombreDistrito' => 'CIPRESES'),
            array('idDistrito' => '30705','idCanton' => '307','nombreDistrito' => 'SANTA ROSA'),
            array('idDistrito' => '30801','idCanton' => '308','nombreDistrito' => 'EL TEJAR'),
            array('idDistrito' => '30802','idCanton' => '308','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '30803','idCanton' => '308','nombreDistrito' => 'TOBOSI'),
            array('idDistrito' => '30804','idCanton' => '308','nombreDistrito' => 'PATIO DE AGUA'),
            array('idDistrito' => '40101','idCanton' => '401','nombreDistrito' => 'HEREDIA'),
            array('idDistrito' => '40102','idCanton' => '401','nombreDistrito' => 'MERCEDES'),
            array('idDistrito' => '40103','idCanton' => '401','nombreDistrito' => 'SAN FRANCISCO'),
            array('idDistrito' => '40104','idCanton' => '401','nombreDistrito' => 'ULLOA'),
            array('idDistrito' => '40105','idCanton' => '401','nombreDistrito' => 'VARABLANCA'),
            array('idDistrito' => '40201','idCanton' => '402','nombreDistrito' => 'BARVA'),
            array('idDistrito' => '40202','idCanton' => '402','nombreDistrito' => 'SAN PEDRO'),
            array('idDistrito' => '40203','idCanton' => '402','nombreDistrito' => 'SAN PABLO'),
            array('idDistrito' => '40204','idCanton' => '402','nombreDistrito' => 'SAN ROQUE'),
            array('idDistrito' => '40205','idCanton' => '402','nombreDistrito' => 'SANTA LUCÍA'),
            array('idDistrito' => '40206','idCanton' => '402','nombreDistrito' => 'SAN JOSÉ DE LA MONTAÑA'),
            array('idDistrito' => '40301','idCanton' => '403','nombreDistrito' => 'SANTO DOMINGO'),
            array('idDistrito' => '40302','idCanton' => '403','nombreDistrito' => 'SAN VICENTE'),
            array('idDistrito' => '40303','idCanton' => '403','nombreDistrito' => 'SAN MIGUEL'),
            array('idDistrito' => '40304','idCanton' => '403','nombreDistrito' => 'PARACITO'),
            array('idDistrito' => '40305','idCanton' => '403','nombreDistrito' => 'SANTO TOMÁS'),
            array('idDistrito' => '40306','idCanton' => '403','nombreDistrito' => 'SANTA ROSA'),
            array('idDistrito' => '40307','idCanton' => '403','nombreDistrito' => 'TURES'),
            array('idDistrito' => '40308','idCanton' => '403','nombreDistrito' => 'PARÁ'),
            array('idDistrito' => '40401','idCanton' => '404','nombreDistrito' => 'SANTA BÁRBARA'),
            array('idDistrito' => '40402','idCanton' => '404','nombreDistrito' => 'SAN PEDRO'),
            array('idDistrito' => '40403','idCanton' => '404','nombreDistrito' => 'SAN JUAN'),
            array('idDistrito' => '40404','idCanton' => '404','nombreDistrito' => 'JESÚS'),
            array('idDistrito' => '40405','idCanton' => '404','nombreDistrito' => 'SANTO DOMINGO DEL ROBLE'),
            array('idDistrito' => '40406','idCanton' => '404','nombreDistrito' => 'PURABA'),
            array('idDistrito' => '40501','idCanton' => '405','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '40502','idCanton' => '405','nombreDistrito' => 'SAN JOSECITO'),
            array('idDistrito' => '40503','idCanton' => '405','nombreDistrito' => 'SANTIAGO'),
            array('idDistrito' => '40504','idCanton' => '405','nombreDistrito' => 'ANGELES'),
            array('idDistrito' => '40505','idCanton' => '405','nombreDistrito' => 'CONCEPCIÓN'),
            array('idDistrito' => '40601','idCanton' => '406','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '40602','idCanton' => '406','nombreDistrito' => 'SAN JOSÉ'),
            array('idDistrito' => '40603','idCanton' => '406','nombreDistrito' => 'CONCEPCIÓN'),
            array('idDistrito' => '40604','idCanton' => '406','nombreDistrito' => 'SAN FRANCISCO'),
            array('idDistrito' => '40701','idCanton' => '407','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '40702','idCanton' => '407','nombreDistrito' => 'LA RIBERA'),
            array('idDistrito' => '40703','idCanton' => '407','nombreDistrito' => 'ASUNCIÓN'),
            array('idDistrito' => '40801','idCanton' => '408','nombreDistrito' => 'SAN JOAQUÍN'),
            array('idDistrito' => '40802','idCanton' => '408','nombreDistrito' => 'BARRANTES'),
            array('idDistrito' => '40803','idCanton' => '408','nombreDistrito' => 'LLORENTE'),
            array('idDistrito' => '40901','idCanton' => '409','nombreDistrito' => 'SAN PABLO'),
            array('idDistrito' => '41001','idCanton' => '410','nombreDistrito' => 'PUERTO VIEJO'),
            array('idDistrito' => '41002','idCanton' => '410','nombreDistrito' => 'LA VIRGEN'),
            array('idDistrito' => '41003','idCanton' => '410','nombreDistrito' => 'HORQUETAS'),
            array('idDistrito' => '41004','idCanton' => '410','nombreDistrito' => 'LLANURAS DE GASPAR'),
            array('idDistrito' => '41005','idCanton' => '410','nombreDistrito' => 'CUREÑA'),
            array('idDistrito' => '50101','idCanton' => '501','nombreDistrito' => 'LIBERIA'),
            array('idDistrito' => '50102','idCanton' => '501','nombreDistrito' => 'CAÑAS DULCES'),
            array('idDistrito' => '50103','idCanton' => '501','nombreDistrito' => 'MAYORGA'),
            array('idDistrito' => '50104','idCanton' => '501','nombreDistrito' => 'NACASCOLO'),
            array('idDistrito' => '50105','idCanton' => '501','nombreDistrito' => 'CURUBANDE'),
            array('idDistrito' => '50201','idCanton' => '502','nombreDistrito' => 'NICOYA'),
            array('idDistrito' => '50202','idCanton' => '502','nombreDistrito' => 'MANSIÓN'),
            array('idDistrito' => '50203','idCanton' => '502','nombreDistrito' => 'SAN ANTONIO'),
            array('idDistrito' => '50204','idCanton' => '502','nombreDistrito' => 'QUEBRADA HONDA'),
            array('idDistrito' => '50205','idCanton' => '502','nombreDistrito' => 'SÁMARA'),
            array('idDistrito' => '50206','idCanton' => '502','nombreDistrito' => 'NÓSARA'),
            array('idDistrito' => '50207','idCanton' => '502','nombreDistrito' => 'BELÉN DE NOSARITA'),
            array('idDistrito' => '50301','idCanton' => '503','nombreDistrito' => 'SANTA CRUZ'),
            array('idDistrito' => '50302','idCanton' => '503','nombreDistrito' => 'BOLSÓN'),
            array('idDistrito' => '50303','idCanton' => '503','nombreDistrito' => 'VEINTISIETE DE ABRIL'),
            array('idDistrito' => '50304','idCanton' => '503','nombreDistrito' => 'TEMPATE'),
            array('idDistrito' => '50305','idCanton' => '503','nombreDistrito' => 'CARTAGENA'),
            array('idDistrito' => '50306','idCanton' => '503','nombreDistrito' => 'CUAJINIQUIL'),
            array('idDistrito' => '50307','idCanton' => '503','nombreDistrito' => 'DIRIÁ'),
            array('idDistrito' => '50308','idCanton' => '503','nombreDistrito' => 'CABO VELAS'),
            array('idDistrito' => '50309','idCanton' => '503','nombreDistrito' => 'TAMARINDO'),
            array('idDistrito' => '50401','idCanton' => '504','nombreDistrito' => 'BAGACES'),
            array('idDistrito' => '50402','idCanton' => '504','nombreDistrito' => 'FORTUNA'),
            array('idDistrito' => '50403','idCanton' => '504','nombreDistrito' => 'MOGOTE'),
            array('idDistrito' => '50404','idCanton' => '504','nombreDistrito' => 'RÍO NARANJO'),
            array('idDistrito' => '50501','idCanton' => '505','nombreDistrito' => 'FILADELFIA'),
            array('idDistrito' => '50502','idCanton' => '505','nombreDistrito' => 'PALMIRA'),
            array('idDistrito' => '50503','idCanton' => '505','nombreDistrito' => 'SARDINAL'),
            array('idDistrito' => '50504','idCanton' => '505','nombreDistrito' => 'BELÉN'),
            array('idDistrito' => '50601','idCanton' => '506','nombreDistrito' => 'CAÑAS'),
            array('idDistrito' => '50602','idCanton' => '506','nombreDistrito' => 'PALMIRA'),
            array('idDistrito' => '50603','idCanton' => '506','nombreDistrito' => 'SAN MIGUEL'),
            array('idDistrito' => '50604','idCanton' => '506','nombreDistrito' => 'BEBEDERO'),
            array('idDistrito' => '50605','idCanton' => '506','nombreDistrito' => 'POROZAL'),
            array('idDistrito' => '50701','idCanton' => '507','nombreDistrito' => 'JUNTAS'),
            array('idDistrito' => '50702','idCanton' => '507','nombreDistrito' => 'SIERRA'),
            array('idDistrito' => '50703','idCanton' => '507','nombreDistrito' => 'SAN JUAN'),
            array('idDistrito' => '50704','idCanton' => '507','nombreDistrito' => 'COLORADO'),
            array('idDistrito' => '50801','idCanton' => '508','nombreDistrito' => 'TILARÁN'),
            array('idDistrito' => '50802','idCanton' => '508','nombreDistrito' => 'QUEBRADA GRANDE'),
            array('idDistrito' => '50803','idCanton' => '508','nombreDistrito' => 'TRONADORA'),
            array('idDistrito' => '50804','idCanton' => '508','nombreDistrito' => 'SANTA ROSA'),
            array('idDistrito' => '50805','idCanton' => '508','nombreDistrito' => 'LÍBANO'),
            array('idDistrito' => '50806','idCanton' => '508','nombreDistrito' => 'TIERRAS MORENAS'),
            array('idDistrito' => '50807','idCanton' => '508','nombreDistrito' => 'ARENAL'),
            array('idDistrito' => '50901','idCanton' => '509','nombreDistrito' => 'CARMONA'),
            array('idDistrito' => '50902','idCanton' => '509','nombreDistrito' => 'SANTA RITA'),
            array('idDistrito' => '50903','idCanton' => '509','nombreDistrito' => 'ZAPOTAL'),
            array('idDistrito' => '50904','idCanton' => '509','nombreDistrito' => 'SAN PABLO'),
            array('idDistrito' => '50905','idCanton' => '509','nombreDistrito' => 'PORVENIR'),
            array('idDistrito' => '50906','idCanton' => '509','nombreDistrito' => 'BEJUCO'),
            array('idDistrito' => '51001','idCanton' => '510','nombreDistrito' => 'LA CRUZ'),
            array('idDistrito' => '51002','idCanton' => '510','nombreDistrito' => 'SANTA CECILIA'),
            array('idDistrito' => '51003','idCanton' => '510','nombreDistrito' => 'GARITA'),
            array('idDistrito' => '51004','idCanton' => '510','nombreDistrito' => 'SANTA ELENA'),
            array('idDistrito' => '51101','idCanton' => '511','nombreDistrito' => 'HOJANCHA'),
            array('idDistrito' => '51102','idCanton' => '511','nombreDistrito' => 'MONTE ROMO'),
            array('idDistrito' => '51103','idCanton' => '511','nombreDistrito' => 'PUERTO CARRILLO'),
            array('idDistrito' => '51104','idCanton' => '511','nombreDistrito' => 'HUACAS'),
            array('idDistrito' => '60101','idCanton' => '601','nombreDistrito' => 'PUNTARENAS'),
            array('idDistrito' => '60102','idCanton' => '601','nombreDistrito' => 'PITAHAYA'),
            array('idDistrito' => '60103','idCanton' => '601','nombreDistrito' => 'CHOMES'),
            array('idDistrito' => '60104','idCanton' => '601','nombreDistrito' => 'LEPANTO'),
            array('idDistrito' => '60105','idCanton' => '601','nombreDistrito' => 'PAQUERA'),
            array('idDistrito' => '60106','idCanton' => '601','nombreDistrito' => 'MANZANILLO'),
            array('idDistrito' => '60107','idCanton' => '601','nombreDistrito' => 'GUACIMAL'),
            array('idDistrito' => '60108','idCanton' => '601','nombreDistrito' => 'BARRANCA'),
            array('idDistrito' => '60109','idCanton' => '601','nombreDistrito' => 'MONTE VERDE'),
            array('idDistrito' => '60110','idCanton' => '601','nombreDistrito' => 'ISLA DEL COCO'),
            array('idDistrito' => '60111','idCanton' => '601','nombreDistrito' => 'CÓBANO'),
            array('idDistrito' => '60112','idCanton' => '601','nombreDistrito' => 'CHACARITA'),
            array('idDistrito' => '60113','idCanton' => '601','nombreDistrito' => 'CHIRA'),
            array('idDistrito' => '60114','idCanton' => '601','nombreDistrito' => 'ACAPULCO'),
            array('idDistrito' => '60115','idCanton' => '601','nombreDistrito' => 'ROBLE'),
            array('idDistrito' => '60116','idCanton' => '601','nombreDistrito' => 'ARANCIBIA'),
            array('idDistrito' => '60201','idCanton' => '602','nombreDistrito' => 'ESPÍRITU SANTO'),
            array('idDistrito' => '60202','idCanton' => '602','nombreDistrito' => 'SAN JUAN GRANDE'),
            array('idDistrito' => '60203','idCanton' => '602','nombreDistrito' => 'MACACONA'),
            array('idDistrito' => '60204','idCanton' => '602','nombreDistrito' => 'SAN RAFAEL'),
            array('idDistrito' => '60205','idCanton' => '602','nombreDistrito' => 'SAN JERÓNIMO'),
            array('idDistrito' => '60301','idCanton' => '603','nombreDistrito' => 'BUENOS AIRES'),
            array('idDistrito' => '60302','idCanton' => '603','nombreDistrito' => 'VOLCÁN'),
            array('idDistrito' => '60303','idCanton' => '603','nombreDistrito' => 'POTRERO GRANDE'),
            array('idDistrito' => '60304','idCanton' => '603','nombreDistrito' => 'BORUCA'),
            array('idDistrito' => '60305','idCanton' => '603','nombreDistrito' => 'PILAS'),
            array('idDistrito' => '60306','idCanton' => '603','nombreDistrito' => 'COLINAS O BAJO DE MAÍZ'),
            array('idDistrito' => '60307','idCanton' => '603','nombreDistrito' => 'CHÁNGUENA'),
            array('idDistrito' => '60308','idCanton' => '603','nombreDistrito' => 'BIOLEY'),
            array('idDistrito' => '60309','idCanton' => '603','nombreDistrito' => 'BRUNKA'),
            array('idDistrito' => '60401','idCanton' => '604','nombreDistrito' => 'MIRAMAR'),
            array('idDistrito' => '60402','idCanton' => '604','nombreDistrito' => 'UNIÓN'),
            array('idDistrito' => '60403','idCanton' => '604','nombreDistrito' => 'SAN ISIDRO'),
            array('idDistrito' => '60501','idCanton' => '605','nombreDistrito' => 'PUERTO CORTÉS'),
            array('idDistrito' => '60502','idCanton' => '605','nombreDistrito' => 'PALMAR'),
            array('idDistrito' => '60503','idCanton' => '605','nombreDistrito' => 'SIERPE'),
            array('idDistrito' => '60504','idCanton' => '605','nombreDistrito' => 'BAHÍA BALLENA'),
            array('idDistrito' => '60505','idCanton' => '605','nombreDistrito' => 'PIEDRAS BLANCAS'),
            array('idDistrito' => '60601','idCanton' => '606','nombreDistrito' => 'QUEPOS'),
            array('idDistrito' => '60602','idCanton' => '606','nombreDistrito' => 'SAVEGRE'),
            array('idDistrito' => '60603','idCanton' => '606','nombreDistrito' => 'NARANJITO'),
            array('idDistrito' => '60701','idCanton' => '607','nombreDistrito' => 'GOLFITO'),
            array('idDistrito' => '60702','idCanton' => '607','nombreDistrito' => 'PUERTO JIMÉNEZ'),
            array('idDistrito' => '60703','idCanton' => '607','nombreDistrito' => 'GUAYCARÁ'),
            array('idDistrito' => '60704','idCanton' => '607','nombreDistrito' => 'PAVON'),
            array('idDistrito' => '60801','idCanton' => '608','nombreDistrito' => 'SAN VITO'),
            array('idDistrito' => '60802','idCanton' => '608','nombreDistrito' => 'SABALITO'),
            array('idDistrito' => '60803','idCanton' => '608','nombreDistrito' => 'AGUA BUENA'),
            array('idDistrito' => '60804','idCanton' => '608','nombreDistrito' => 'LIMONCITO'),
            array('idDistrito' => '60805','idCanton' => '608','nombreDistrito' => 'PITTIER'),
            array('idDistrito' => '60901','idCanton' => '609','nombreDistrito' => 'PARRITA'),
            array('idDistrito' => '61001','idCanton' => '610','nombreDistrito' => 'CORREDOR'),
            array('idDistrito' => '61002','idCanton' => '610','nombreDistrito' => 'LA CUESTA'),
            array('idDistrito' => '61003','idCanton' => '610','nombreDistrito' => 'PASO CANOAS'),
            array('idDistrito' => '61004','idCanton' => '610','nombreDistrito' => 'LAUREL'),
            array('idDistrito' => '61101','idCanton' => '611','nombreDistrito' => 'JACÓ'),
            array('idDistrito' => '61102','idCanton' => '611','nombreDistrito' => 'TÁRCOLES'),
            array('idDistrito' => '70101','idCanton' => '701','nombreDistrito' => 'LIMÓN'),
            array('idDistrito' => '70102','idCanton' => '701','nombreDistrito' => 'VALLE LA ESTRELLA'),
            array('idDistrito' => '70103','idCanton' => '701','nombreDistrito' => 'RÍO BLANCO'),
            array('idDistrito' => '70104','idCanton' => '701','nombreDistrito' => 'MATAMA'),
            array('idDistrito' => '70201','idCanton' => '702','nombreDistrito' => 'GUÁPILES'),
            array('idDistrito' => '70202','idCanton' => '702','nombreDistrito' => 'JIMÉNEZ'),
            array('idDistrito' => '70203','idCanton' => '702','nombreDistrito' => 'RITA'),
            array('idDistrito' => '70204','idCanton' => '702','nombreDistrito' => 'ROXANA'),
            array('idDistrito' => '70205','idCanton' => '702','nombreDistrito' => 'CARIARI'),
            array('idDistrito' => '70206','idCanton' => '702','nombreDistrito' => 'COLORADO'),
            array('idDistrito' => '70301','idCanton' => '703','nombreDistrito' => 'SIQUIRRES'),
            array('idDistrito' => '70302','idCanton' => '703','nombreDistrito' => 'PACUARITO'),
            array('idDistrito' => '70303','idCanton' => '703','nombreDistrito' => 'FLORIDA'),
            array('idDistrito' => '70304','idCanton' => '703','nombreDistrito' => 'GERMANIA'),
            array('idDistrito' => '70305','idCanton' => '703','nombreDistrito' => 'CAIRO'),
            array('idDistrito' => '70306','idCanton' => '703','nombreDistrito' => 'ALEGRÍA'),
            array('idDistrito' => '70401','idCanton' => '704','nombreDistrito' => 'BRATSI'),
            array('idDistrito' => '70402','idCanton' => '704','nombreDistrito' => 'SIXAOLA'),
            array('idDistrito' => '70403','idCanton' => '704','nombreDistrito' => 'CAHUITA'),
            array('idDistrito' => '70404','idCanton' => '704','nombreDistrito' => 'TELIRE'),
            array('idDistrito' => '70501','idCanton' => '705','nombreDistrito' => 'MATINA'),
            array('idDistrito' => '70502','idCanton' => '705','nombreDistrito' => 'BATÁN'),
            array('idDistrito' => '70503','idCanton' => '705','nombreDistrito' => 'CARRANDÍ'),
            array('idDistrito' => '70601','idCanton' => '706','nombreDistrito' => 'GUÁCIMO'),
            array('idDistrito' => '70602','idCanton' => '706','nombreDistrito' => 'MERCEDES'),
            array('idDistrito' => '70603','idCanton' => '706','nombreDistrito' => 'POCORA'),
            array('idDistrito' => '70604','idCanton' => '706','nombreDistrito' => 'RÍO JIMÉNEZ'),
            array('idDistrito' => '70605','idCanton' => '706','nombreDistrito' => 'DUACARÍ')
      );
        $names = [
            'Victor',
            'Vanessa',
            'Franklin',
            'Marisela',
            'Diego',
            'Katherine',
            'Jesús',
            'Sussana',
            'Farlen',
            'Sharon',
            'Alexander',
            'María José',
            'Gustavo',
            'Karol',
        ];

        $last_names = [
            'Piedra',
            'Marín',
            'Duarte',
            'Davila',
            'Rodríguez',
            'Pacheco',
            'Calderón',
            'Segura',
            'Sibaja',
            'Vargas',
            'Arce',
            'Alpízar',
        ];

        $mailers = [
            'gmail.com',
            'hotmail.com',
            'ucr.ac.cr',
            'hotmail.es',
            'ucrso.info',
            'yahoo.com',
            'outlook.com',
        ];

        User::create([
            'name' => 'Diego',
            'email' => 'diegojopiedra@gmail.com',
            'password' => bcrypt('1234'),
            'identity_card' => 207400490,
            'last_name' => 'Piedra Araya',
            'home_phone' => 0,
            'cell_phone' => rand(30000000,89999999),
            'next_update_time' => '2017-04-06',
            'active' => true,
            'role_id' => 1,
            'id_district' => 21001,
        ]);
        $nums = array();
        array_push($nums, 207400490);

        $unwanted_array = array(    'Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
                            'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U',
                            'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss', 'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c',
                            'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o',
                            'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y', ' '=>'.' );
//$str = strtr( $str, $unwanted_array );

        for ($i=1; $i < 20; $i++) { 
            $name = $names[rand(0,count($names)-1)]; 
            $last_name_1 = $last_names[rand(0,count($last_names)-1)];
            $last_name_2 = $last_names[rand(0,count($last_names)-1)];
            User::create([
                'name' => $name,
                'email' => strtolower(strtr( $name, $unwanted_array )) . "." . strtolower(strtr( $last_name_1, $unwanted_array )) . $i ."@" . $mailers[rand(0,count($mailers)-1)],
                'password' => bcrypt('1234'),
                'identity_card' => $this->getCard($nums),
                'last_name' => $last_name_1 . " " . $last_name_2,
                'home_phone' => rand(30000000,89999999),
                'cell_phone' => rand(30000000,89999999),
                'next_update_time' => (rand(15,17) + 2000) . '-' . rand(1,12) . '-'. rand(1,28),
                'active' => true,
                'role_id' => rand(1,3),
                'id_district' => $Distritos[rand(0, count($Distritos)-1)]['idDistrito'],
                'direction' => "Contiguo a UCR Tacares, Grecia, Alajuela, Costa Rica",
            ]);
        }
    }

    public function getCard($nums)
    {
        do{
            $num = 0; 
            $num = rand(1,7) * 100000000;
            $num += rand(100,999) * 10000;
            $num += rand(100,999);
            $sNum = strval($num);
        }while(in_array($sNum,$nums));
        array_push($nums, $sNum);
        return $num;
    }
}
