<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `gymrug`
//

// `gymrug`.`Cantones`
$Cantones = array(
  array('idCanton' => '101','idProvincia' => '1','nombreCanton' => 'San José'),
  array('idCanton' => '102','idProvincia' => '1','nombreCanton' => 'Escazú'),
  array('idCanton' => '103','idProvincia' => '1','nombreCanton' => 'Desamparados'),
  array('idCanton' => '104','idProvincia' => '1','nombreCanton' => 'Puriscal'),
  array('idCanton' => '105','idProvincia' => '1','nombreCanton' => 'Tarrazú'),
  array('idCanton' => '106','idProvincia' => '1','nombreCanton' => 'Aserrí'),
  array('idCanton' => '107','idProvincia' => '1','nombreCanton' => 'Mora'),
  array('idCanton' => '108','idProvincia' => '1','nombreCanton' => 'Goicoechea'),
  array('idCanton' => '109','idProvincia' => '1','nombreCanton' => 'Santa Ana'),
  array('idCanton' => '110','idProvincia' => '1','nombreCanton' => 'Alajuelita'),
  array('idCanton' => '111','idProvincia' => '1','nombreCanton' => 'Vasquez de Coronado'),
  array('idCanton' => '112','idProvincia' => '1','nombreCanton' => 'Acosta'),
  array('idCanton' => '113','idProvincia' => '1','nombreCanton' => 'Tibás'),
  array('idCanton' => '114','idProvincia' => '1','nombreCanton' => 'Moravia'),
  array('idCanton' => '115','idProvincia' => '1','nombreCanton' => 'Montes de Oca'),
  array('idCanton' => '116','idProvincia' => '1','nombreCanton' => 'Turrubares'),
  array('idCanton' => '117','idProvincia' => '1','nombreCanton' => 'Dota'),
  array('idCanton' => '118','idProvincia' => '1','nombreCanton' => 'Curridabat'),
  array('idCanton' => '119','idProvincia' => '1','nombreCanton' => 'Pérez Zeledón'),
  array('idCanton' => '120','idProvincia' => '1','nombreCanton' => 'León Cortés'),
  array('idCanton' => '201','idProvincia' => '2','nombreCanton' => 'Alajuela'),
  array('idCanton' => '202','idProvincia' => '2','nombreCanton' => 'San Ramón'),
  array('idCanton' => '203','idProvincia' => '2','nombreCanton' => 'Grecia'),
  array('idCanton' => '204','idProvincia' => '2','nombreCanton' => 'San Mateo'),
  array('idCanton' => '205','idProvincia' => '2','nombreCanton' => 'Atenas'),
  array('idCanton' => '206','idProvincia' => '2','nombreCanton' => 'Naranjo'),
  array('idCanton' => '207','idProvincia' => '2','nombreCanton' => 'Palmares'),
  array('idCanton' => '208','idProvincia' => '2','nombreCanton' => 'Poás'),
  array('idCanton' => '209','idProvincia' => '2','nombreCanton' => 'Orotina'),
  array('idCanton' => '210','idProvincia' => '2','nombreCanton' => 'San Carlos'),
  array('idCanton' => '211','idProvincia' => '2','nombreCanton' => 'Alfaro Ruiz'),
  array('idCanton' => '212','idProvincia' => '2','nombreCanton' => 'Valverde Vega'),
  array('idCanton' => '213','idProvincia' => '2','nombreCanton' => 'Upala'),
  array('idCanton' => '214','idProvincia' => '2','nombreCanton' => 'Los Chiles'),
  array('idCanton' => '215','idProvincia' => '2','nombreCanton' => 'Guatuso'),
  array('idCanton' => '301','idProvincia' => '4','nombreCanton' => 'Cartago'),
  array('idCanton' => '302','idProvincia' => '4','nombreCanton' => 'Paraíso'),
  array('idCanton' => '303','idProvincia' => '4','nombreCanton' => 'La Unión'),
  array('idCanton' => '304','idProvincia' => '4','nombreCanton' => 'Jiménez'),
  array('idCanton' => '305','idProvincia' => '4','nombreCanton' => 'Turrialba'),
  array('idCanton' => '306','idProvincia' => '4','nombreCanton' => 'Alvarado'),
  array('idCanton' => '307','idProvincia' => '4','nombreCanton' => 'Oreamuno'),
  array('idCanton' => '308','idProvincia' => '4','nombreCanton' => 'El Guarco'),
  array('idCanton' => '401','idProvincia' => '3','nombreCanton' => 'Heredia'),
  array('idCanton' => '402','idProvincia' => '3','nombreCanton' => 'Barva'),
  array('idCanton' => '403','idProvincia' => '3','nombreCanton' => 'Santo Domingo'),
  array('idCanton' => '404','idProvincia' => '3','nombreCanton' => 'Santa Bárbara'),
  array('idCanton' => '405','idProvincia' => '3','nombreCanton' => 'San Rafael'),
  array('idCanton' => '406','idProvincia' => '3','nombreCanton' => 'San Isidro'),
  array('idCanton' => '407','idProvincia' => '3','nombreCanton' => 'Belén'),
  array('idCanton' => '408','idProvincia' => '3','nombreCanton' => 'Flores'),
  array('idCanton' => '409','idProvincia' => '3','nombreCanton' => 'San Pablo'),
  array('idCanton' => '410','idProvincia' => '3','nombreCanton' => 'Sarapiquí '),
  array('idCanton' => '501','idProvincia' => '6','nombreCanton' => 'Liberia'),
  array('idCanton' => '502','idProvincia' => '6','nombreCanton' => 'Nicoya'),
  array('idCanton' => '503','idProvincia' => '6','nombreCanton' => 'Santa Cruz'),
  array('idCanton' => '504','idProvincia' => '6','nombreCanton' => 'Bagaces'),
  array('idCanton' => '505','idProvincia' => '6','nombreCanton' => 'Carrillo'),
  array('idCanton' => '506','idProvincia' => '6','nombreCanton' => 'Cañas'),
  array('idCanton' => '507','idProvincia' => '6','nombreCanton' => 'Abangares'),
  array('idCanton' => '508','idProvincia' => '6','nombreCanton' => 'Tilarán'),
  array('idCanton' => '509','idProvincia' => '6','nombreCanton' => 'Nandayure'),
  array('idCanton' => '510','idProvincia' => '6','nombreCanton' => 'La Cruz'),
  array('idCanton' => '511','idProvincia' => '6','nombreCanton' => 'Hojancha'),
  array('idCanton' => '601','idProvincia' => '5','nombreCanton' => 'Puntarenas'),
  array('idCanton' => '602','idProvincia' => '5','nombreCanton' => 'Esparza'),
  array('idCanton' => '603','idProvincia' => '5','nombreCanton' => 'Buenos Aires'),
  array('idCanton' => '604','idProvincia' => '5','nombreCanton' => 'Montes de Oro'),
  array('idCanton' => '605','idProvincia' => '5','nombreCanton' => 'Osa'),
  array('idCanton' => '606','idProvincia' => '5','nombreCanton' => 'Aguirre'),
  array('idCanton' => '607','idProvincia' => '5','nombreCanton' => 'Golfito'),
  array('idCanton' => '608','idProvincia' => '5','nombreCanton' => 'Coto Brus'),
  array('idCanton' => '609','idProvincia' => '5','nombreCanton' => 'Parrita'),
  array('idCanton' => '610','idProvincia' => '5','nombreCanton' => 'Corredores'),
  array('idCanton' => '611','idProvincia' => '5','nombreCanton' => 'Garabito'),
  array('idCanton' => '701','idProvincia' => '7','nombreCanton' => 'Limón'),
  array('idCanton' => '702','idProvincia' => '7','nombreCanton' => 'Pococí'),
  array('idCanton' => '703','idProvincia' => '7','nombreCanton' => 'Siquirres '),
  array('idCanton' => '704','idProvincia' => '7','nombreCanton' => 'Talamanca'),
  array('idCanton' => '705','idProvincia' => '7','nombreCanton' => 'Matina'),
  array('idCanton' => '706','idProvincia' => '7','nombreCanton' => 'Guácimo')
);

// `gymrug`.`Distritos`
$Distritos = array(
  array('idDistrito' => '10101','idCanton' => '101','nombreDistrito' => 'Carmen'),
  array('idDistrito' => '10102','idCanton' => '101','nombreDistrito' => 'Merced'),
  array('idDistrito' => '10103','idCanton' => '101','nombreDistrito' => 'Hospital'),
  array('idDistrito' => '10104','idCanton' => '101','nombreDistrito' => 'Catedral'),
  array('idDistrito' => '10105','idCanton' => '101','nombreDistrito' => 'Zapote'),
  array('idDistrito' => '10106','idCanton' => '101','nombreDistrito' => 'San Francisco de Dos Ríos'),
  array('idDistrito' => '10107','idCanton' => '101','nombreDistrito' => 'Uruca'),
  array('idDistrito' => '10108','idCanton' => '101','nombreDistrito' => 'Mata Redonda'),
  array('idDistrito' => '10109','idCanton' => '101','nombreDistrito' => 'Pavas'),
  array('idDistrito' => '10110','idCanton' => '101','nombreDistrito' => 'Hatillo'),
  array('idDistrito' => '10111','idCanton' => '101','nombreDistrito' => 'San Sebastián'),
  array('idDistrito' => '10201','idCanton' => '102','nombreDistrito' => 'Escazú'),
  array('idDistrito' => '10202','idCanton' => '102','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '10203','idCanton' => '102','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '10301','idCanton' => '103','nombreDistrito' => 'Desamparados'),
  array('idDistrito' => '10302','idCanton' => '103','nombreDistrito' => 'San Miguel'),
  array('idDistrito' => '10303','idCanton' => '103','nombreDistrito' => 'San Juan de Dios'),
  array('idDistrito' => '10304','idCanton' => '103','nombreDistrito' => 'San Rafael Arriba'),
  array('idDistrito' => '10305','idCanton' => '103','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '10306','idCanton' => '103','nombreDistrito' => 'Frailes'),
  array('idDistrito' => '10307','idCanton' => '103','nombreDistrito' => 'Patarrá'),
  array('idDistrito' => '10308','idCanton' => '103','nombreDistrito' => 'San Cristóbal'),
  array('idDistrito' => '10309','idCanton' => '103','nombreDistrito' => 'Rosario'),
  array('idDistrito' => '10310','idCanton' => '103','nombreDistrito' => 'Damas'),
  array('idDistrito' => '10311','idCanton' => '103','nombreDistrito' => 'San Rafael Abajo'),
  array('idDistrito' => '10312','idCanton' => '103','nombreDistrito' => 'Gravilias'),
  array('idDistrito' => '10313','idCanton' => '103','nombreDistrito' => 'Los Guido'),
  array('idDistrito' => '10401','idCanton' => '104','nombreDistrito' => 'Santiago'),
  array('idDistrito' => '10402','idCanton' => '104','nombreDistrito' => 'Mercedes Sur'),
  array('idDistrito' => '10403','idCanton' => '104','nombreDistrito' => 'Barbacoas'),
  array('idDistrito' => '10404','idCanton' => '104','nombreDistrito' => 'Grifo Alto'),
  array('idDistrito' => '10405','idCanton' => '104','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '10406','idCanton' => '104','nombreDistrito' => 'Candelaria'),
  array('idDistrito' => '10407','idCanton' => '104','nombreDistrito' => 'Desamparaditos'),
  array('idDistrito' => '10408','idCanton' => '104','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '10409','idCanton' => '104','nombreDistrito' => 'Chires'),
  array('idDistrito' => '10501','idCanton' => '105','nombreDistrito' => 'San Marcos'),
  array('idDistrito' => '10502','idCanton' => '105','nombreDistrito' => 'San Lorenzo'),
  array('idDistrito' => '10503','idCanton' => '105','nombreDistrito' => 'San Carlos'),
  array('idDistrito' => '10601','idCanton' => '106','nombreDistrito' => 'Aserrí'),
  array('idDistrito' => '10602','idCanton' => '106','nombreDistrito' => 'Tarbaca o Praga'),
  array('idDistrito' => '10603','idCanton' => '106','nombreDistrito' => 'Vuelta de Jorco'),
  array('idDistrito' => '10604','idCanton' => '106','nombreDistrito' => 'San Gabriel'),
  array('idDistrito' => '10605','idCanton' => '106','nombreDistrito' => 'La Legua'),
  array('idDistrito' => '10606','idCanton' => '106','nombreDistrito' => 'Monterrey'),
  array('idDistrito' => '10607','idCanton' => '106','nombreDistrito' => 'Salitrillos'),
  array('idDistrito' => '10701','idCanton' => '107','nombreDistrito' => 'Colón'),
  array('idDistrito' => '10702','idCanton' => '107','nombreDistrito' => 'Guayabo'),
  array('idDistrito' => '10703','idCanton' => '107','nombreDistrito' => 'Tabarcia'),
  array('idDistrito' => '10704','idCanton' => '107','nombreDistrito' => 'Piedras Negras'),
  array('idDistrito' => '10705','idCanton' => '107','nombreDistrito' => 'Picagres'),
  array('idDistrito' => '10801','idCanton' => '108','nombreDistrito' => 'Guadalupe'),
  array('idDistrito' => '10802','idCanton' => '108','nombreDistrito' => 'San Francisco'),
  array('idDistrito' => '10803','idCanton' => '108','nombreDistrito' => 'Calle Blancos'),
  array('idDistrito' => '10804','idCanton' => '108','nombreDistrito' => 'Mata de Plátano'),
  array('idDistrito' => '10805','idCanton' => '108','nombreDistrito' => 'Ipís'),
  array('idDistrito' => '10806','idCanton' => '108','nombreDistrito' => 'Rancho Redondo'),
  array('idDistrito' => '10807','idCanton' => '108','nombreDistrito' => 'Purral'),
  array('idDistrito' => '10901','idCanton' => '109','nombreDistrito' => 'Santa Ana'),
  array('idDistrito' => '10902','idCanton' => '109','nombreDistrito' => 'Salitral'),
  array('idDistrito' => '10903','idCanton' => '109','nombreDistrito' => 'Pozos o Concepción'),
  array('idDistrito' => '10904','idCanton' => '109','nombreDistrito' => 'Uruca o San Joaquín'),
  array('idDistrito' => '10905','idCanton' => '109','nombreDistrito' => 'Piedades'),
  array('idDistrito' => '10906','idCanton' => '109','nombreDistrito' => 'Brasil'),
  array('idDistrito' => '11001','idCanton' => '110','nombreDistrito' => 'Alajuelita'),
  array('idDistrito' => '11002','idCanton' => '110','nombreDistrito' => 'San Josecito'),
  array('idDistrito' => '11003','idCanton' => '110','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '11004','idCanton' => '110','nombreDistrito' => 'Concepción'),
  array('idDistrito' => '11005','idCanton' => '110','nombreDistrito' => 'San Felipe'),
  array('idDistrito' => '11101','idCanton' => '111','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '11102','idCanton' => '111','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '11103','idCanton' => '111','nombreDistrito' => 'Dulce Nombre de Jesús'),
  array('idDistrito' => '11104','idCanton' => '111','nombreDistrito' => 'Patalillo'),
  array('idDistrito' => '11105','idCanton' => '111','nombreDistrito' => 'Cascajal'),
  array('idDistrito' => '11201','idCanton' => '112','nombreDistrito' => 'San Ignacio'),
  array('idDistrito' => '11202','idCanton' => '112','nombreDistrito' => 'Guaitil'),
  array('idDistrito' => '11203','idCanton' => '112','nombreDistrito' => 'Palmichal'),
  array('idDistrito' => '11204','idCanton' => '112','nombreDistrito' => 'Cangrejal'),
  array('idDistrito' => '11205','idCanton' => '112','nombreDistrito' => 'Sabanillas'),
  array('idDistrito' => '11301','idCanton' => '113','nombreDistrito' => 'San Juan'),
  array('idDistrito' => '11302','idCanton' => '113','nombreDistrito' => 'Cinco Esquinas'),
  array('idDistrito' => '11303','idCanton' => '113','nombreDistrito' => 'Anselmo Llorente'),
  array('idDistrito' => '11304','idCanton' => '113','nombreDistrito' => 'León XIII'),
  array('idDistrito' => '11305','idCanton' => '113','nombreDistrito' => 'Colima'),
  array('idDistrito' => '11401','idCanton' => '114','nombreDistrito' => 'San Vicente'),
  array('idDistrito' => '11402','idCanton' => '114','nombreDistrito' => 'San Jerónimo'),
  array('idDistrito' => '11403','idCanton' => '114','nombreDistrito' => 'Trinidad'),
  array('idDistrito' => '11501','idCanton' => '115','nombreDistrito' => 'San Pedro'),
  array('idDistrito' => '11502','idCanton' => '115','nombreDistrito' => 'Sabanilla'),
  array('idDistrito' => '11503','idCanton' => '115','nombreDistrito' => 'Mercedes o Betania'),
  array('idDistrito' => '11504','idCanton' => '115','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '11601','idCanton' => '116','nombreDistrito' => 'San Pablo'),
  array('idDistrito' => '11602','idCanton' => '116','nombreDistrito' => 'San Pedro'),
  array('idDistrito' => '11603','idCanton' => '116','nombreDistrito' => 'San Juan de Mata'),
  array('idDistrito' => '11604','idCanton' => '116','nombreDistrito' => 'San Luis'),
  array('idDistrito' => '11605','idCanton' => '116','nombreDistrito' => 'Cárara'),
  array('idDistrito' => '11701','idCanton' => '117','nombreDistrito' => 'Santa María'),
  array('idDistrito' => '11702','idCanton' => '117','nombreDistrito' => 'Jardín'),
  array('idDistrito' => '11703','idCanton' => '117','nombreDistrito' => 'Copey'),
  array('idDistrito' => '11801','idCanton' => '118','nombreDistrito' => 'Curridabat'),
  array('idDistrito' => '11802','idCanton' => '118','nombreDistrito' => 'Granadilla'),
  array('idDistrito' => '11803','idCanton' => '118','nombreDistrito' => 'Sánchez'),
  array('idDistrito' => '11804','idCanton' => '118','nombreDistrito' => 'Tirrases'),
  array('idDistrito' => '11901','idCanton' => '119','nombreDistrito' => 'San Isidro de el General'),
  array('idDistrito' => '11902','idCanton' => '119','nombreDistrito' => 'General'),
  array('idDistrito' => '11903','idCanton' => '119','nombreDistrito' => 'Daniel Flores'),
  array('idDistrito' => '11904','idCanton' => '119','nombreDistrito' => 'Rivas'),
  array('idDistrito' => '11905','idCanton' => '119','nombreDistrito' => 'San Pedro'),
  array('idDistrito' => '11906','idCanton' => '119','nombreDistrito' => 'Platanares'),
  array('idDistrito' => '11907','idCanton' => '119','nombreDistrito' => 'Pejibaye'),
  array('idDistrito' => '11908','idCanton' => '119','nombreDistrito' => 'Cajón'),
  array('idDistrito' => '11909','idCanton' => '119','nombreDistrito' => 'Barú'),
  array('idDistrito' => '11910','idCanton' => '119','nombreDistrito' => 'Río Nuevo'),
  array('idDistrito' => '11911','idCanton' => '119','nombreDistrito' => 'Páramo'),
  array('idDistrito' => '12001','idCanton' => '120','nombreDistrito' => 'San Pablo'),
  array('idDistrito' => '12002','idCanton' => '120','nombreDistrito' => 'San Andrés'),
  array('idDistrito' => '12003','idCanton' => '120','nombreDistrito' => 'Llano Bonito'),
  array('idDistrito' => '12004','idCanton' => '120','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '12005','idCanton' => '120','nombreDistrito' => 'Santa Cruz'),
  array('idDistrito' => '12006','idCanton' => '120','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '20101','idCanton' => '201','nombreDistrito' => 'Alajuela'),
  array('idDistrito' => '20102','idCanton' => '201','nombreDistrito' => 'San José'),
  array('idDistrito' => '20103','idCanton' => '201','nombreDistrito' => 'Carrizal'),
  array('idDistrito' => '20104','idCanton' => '201','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '20105','idCanton' => '201','nombreDistrito' => 'Guácima'),
  array('idDistrito' => '20106','idCanton' => '201','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '20107','idCanton' => '201','nombreDistrito' => 'Sabanilla'),
  array('idDistrito' => '20108','idCanton' => '201','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '20109','idCanton' => '201','nombreDistrito' => 'Río Segundo'),
  array('idDistrito' => '20110','idCanton' => '201','nombreDistrito' => 'Desamparados'),
  array('idDistrito' => '20111','idCanton' => '201','nombreDistrito' => 'Turrucares'),
  array('idDistrito' => '20112','idCanton' => '201','nombreDistrito' => 'Tambor'),
  array('idDistrito' => '20113','idCanton' => '201','nombreDistrito' => 'La Garita'),
  array('idDistrito' => '20114','idCanton' => '201','nombreDistrito' => 'Sarapiquí'),
  array('idDistrito' => '20201','idCanton' => '202','nombreDistrito' => 'San Ramón'),
  array('idDistrito' => '20202','idCanton' => '202','nombreDistrito' => 'Santiago'),
  array('idDistrito' => '20203','idCanton' => '202','nombreDistrito' => 'San Juan'),
  array('idDistrito' => '20204','idCanton' => '202','nombreDistrito' => 'Piedades Norte'),
  array('idDistrito' => '20205','idCanton' => '202','nombreDistrito' => 'Piedades Sur'),
  array('idDistrito' => '20206','idCanton' => '202','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '20207','idCanton' => '202','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '20208','idCanton' => '202','nombreDistrito' => 'Angeles'),
  array('idDistrito' => '20209','idCanton' => '202','nombreDistrito' => 'Alfaro'),
  array('idDistrito' => '20210','idCanton' => '202','nombreDistrito' => 'Volio'),
  array('idDistrito' => '20211','idCanton' => '202','nombreDistrito' => 'Concepción'),
  array('idDistrito' => '20212','idCanton' => '202','nombreDistrito' => 'Zapotal'),
  array('idDistrito' => '20213','idCanton' => '202','nombreDistrito' => 'San Isidro de Peñas Blancas'),
  array('idDistrito' => '20301','idCanton' => '203','nombreDistrito' => 'Grecia'),
  array('idDistrito' => '20302','idCanton' => '203','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '20303','idCanton' => '203','nombreDistrito' => 'San José'),
  array('idDistrito' => '20304','idCanton' => '203','nombreDistrito' => 'San Roque'),
  array('idDistrito' => '20305','idCanton' => '203','nombreDistrito' => 'Tacares'),
  array('idDistrito' => '20306','idCanton' => '203','nombreDistrito' => 'Río Cuarto'),
  array('idDistrito' => '20307','idCanton' => '203','nombreDistrito' => 'Puente Piedra'),
  array('idDistrito' => '20308','idCanton' => '203','nombreDistrito' => 'Bolívar'),
  array('idDistrito' => '20401','idCanton' => '204','nombreDistrito' => 'San Mateo'),
  array('idDistrito' => '20402','idCanton' => '204','nombreDistrito' => 'Desmonte'),
  array('idDistrito' => '20403','idCanton' => '204','nombreDistrito' => 'Jesús María'),
  array('idDistrito' => '20501','idCanton' => '205','nombreDistrito' => 'Atenas'),
  array('idDistrito' => '20502','idCanton' => '205','nombreDistrito' => 'Jesús'),
  array('idDistrito' => '20503','idCanton' => '205','nombreDistrito' => 'Mercedes'),
  array('idDistrito' => '20504','idCanton' => '205','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '20505','idCanton' => '205','nombreDistrito' => 'Concepción'),
  array('idDistrito' => '20506','idCanton' => '205','nombreDistrito' => 'San José'),
  array('idDistrito' => '20507','idCanton' => '205','nombreDistrito' => 'Santa Eulalia'),
  array('idDistrito' => '20508','idCanton' => '205','nombreDistrito' => 'Escobal'),
  array('idDistrito' => '20601','idCanton' => '206','nombreDistrito' => 'Naranjo'),
  array('idDistrito' => '20602','idCanton' => '206','nombreDistrito' => 'San Miguel'),
  array('idDistrito' => '20603','idCanton' => '206','nombreDistrito' => 'San José'),
  array('idDistrito' => '20604','idCanton' => '206','nombreDistrito' => 'Cirrí Sur'),
  array('idDistrito' => '20605','idCanton' => '206','nombreDistrito' => 'San Jerónimo'),
  array('idDistrito' => '20606','idCanton' => '206','nombreDistrito' => 'San Juan'),
  array('idDistrito' => '20607','idCanton' => '206','nombreDistrito' => 'Rosario'),
  array('idDistrito' => '20701','idCanton' => '207','nombreDistrito' => 'Palmares'),
  array('idDistrito' => '20702','idCanton' => '207','nombreDistrito' => 'Zaragoza'),
  array('idDistrito' => '20703','idCanton' => '207','nombreDistrito' => 'Buenos Aires'),
  array('idDistrito' => '20704','idCanton' => '207','nombreDistrito' => 'Santiago'),
  array('idDistrito' => '20705','idCanton' => '207','nombreDistrito' => 'Candelaria'),
  array('idDistrito' => '20706','idCanton' => '207','nombreDistrito' => 'Esquipulas'),
  array('idDistrito' => '20707','idCanton' => '207','nombreDistrito' => 'La Granja'),
  array('idDistrito' => '20801','idCanton' => '208','nombreDistrito' => 'San Pedro'),
  array('idDistrito' => '20802','idCanton' => '208','nombreDistrito' => 'San Juan'),
  array('idDistrito' => '20803','idCanton' => '208','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '20804','idCanton' => '208','nombreDistrito' => 'Carrillos'),
  array('idDistrito' => '20805','idCanton' => '208','nombreDistrito' => 'Sabana Redonda'),
  array('idDistrito' => '20901','idCanton' => '209','nombreDistrito' => 'Orotina'),
  array('idDistrito' => '20902','idCanton' => '209','nombreDistrito' => 'Mastate'),
  array('idDistrito' => '20903','idCanton' => '209','nombreDistrito' => 'Hacienda Vieja'),
  array('idDistrito' => '20904','idCanton' => '209','nombreDistrito' => 'Coyolar'),
  array('idDistrito' => '20905','idCanton' => '209','nombreDistrito' => 'Ceiba'),
  array('idDistrito' => '21001','idCanton' => '210','nombreDistrito' => 'Quesada'),
  array('idDistrito' => '21002','idCanton' => '210','nombreDistrito' => 'Florencia'),
  array('idDistrito' => '21003','idCanton' => '210','nombreDistrito' => 'Buenavista'),
  array('idDistrito' => '21004','idCanton' => '210','nombreDistrito' => 'Aguas Zarcas'),
  array('idDistrito' => '21005','idCanton' => '210','nombreDistrito' => 'Venecia'),
  array('idDistrito' => '21006','idCanton' => '210','nombreDistrito' => 'Pital'),
  array('idDistrito' => '21007','idCanton' => '210','nombreDistrito' => 'Fortuna'),
  array('idDistrito' => '21008','idCanton' => '210','nombreDistrito' => 'Tigra'),
  array('idDistrito' => '21009','idCanton' => '210','nombreDistrito' => 'Palmera'),
  array('idDistrito' => '21010','idCanton' => '210','nombreDistrito' => 'Venado'),
  array('idDistrito' => '21011','idCanton' => '210','nombreDistrito' => 'Cutris'),
  array('idDistrito' => '21012','idCanton' => '210','nombreDistrito' => 'Monterrey'),
  array('idDistrito' => '21013','idCanton' => '210','nombreDistrito' => 'Pocosol'),
  array('idDistrito' => '21101','idCanton' => '211','nombreDistrito' => 'Zarcero'),
  array('idDistrito' => '21102','idCanton' => '211','nombreDistrito' => 'Laguna'),
  array('idDistrito' => '21103','idCanton' => '211','nombreDistrito' => 'Tapezco'),
  array('idDistrito' => '21104','idCanton' => '211','nombreDistrito' => 'Guadalupe'),
  array('idDistrito' => '21105','idCanton' => '211','nombreDistrito' => 'Palmira'),
  array('idDistrito' => '21106','idCanton' => '211','nombreDistrito' => 'Zapote'),
  array('idDistrito' => '21107','idCanton' => '211','nombreDistrito' => 'Las Brisas'),
  array('idDistrito' => '21201','idCanton' => '212','nombreDistrito' => 'Sarchí Norte'),
  array('idDistrito' => '21202','idCanton' => '212','nombreDistrito' => 'Sarchí Sur'),
  array('idDistrito' => '21203','idCanton' => '212','nombreDistrito' => 'Toro Amarillo'),
  array('idDistrito' => '21204','idCanton' => '212','nombreDistrito' => 'San Pedro'),
  array('idDistrito' => '21205','idCanton' => '212','nombreDistrito' => 'Rodríguez'),
  array('idDistrito' => '21301','idCanton' => '213','nombreDistrito' => 'Upala'),
  array('idDistrito' => '21302','idCanton' => '213','nombreDistrito' => 'Aguas Claras'),
  array('idDistrito' => '21303','idCanton' => '213','nombreDistrito' => 'San José o Pizote'),
  array('idDistrito' => '21304','idCanton' => '213','nombreDistrito' => 'Bijagua'),
  array('idDistrito' => '21305','idCanton' => '213','nombreDistrito' => 'Delicias'),
  array('idDistrito' => '21306','idCanton' => '213','nombreDistrito' => 'Dos Ríos'),
  array('idDistrito' => '21307','idCanton' => '213','nombreDistrito' => 'Yolillal'),
  array('idDistrito' => '21401','idCanton' => '214','nombreDistrito' => 'Los Chiles'),
  array('idDistrito' => '21402','idCanton' => '214','nombreDistrito' => 'Caño Negro'),
  array('idDistrito' => '21403','idCanton' => '214','nombreDistrito' => 'Amparo'),
  array('idDistrito' => '21404','idCanton' => '214','nombreDistrito' => 'San Jorge'),
  array('idDistrito' => '21501','idCanton' => '215','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '21502','idCanton' => '215','nombreDistrito' => 'Buenavista'),
  array('idDistrito' => '21503','idCanton' => '215','nombreDistrito' => 'Cote'),
  array('idDistrito' => '30101','idCanton' => '301','nombreDistrito' => 'Oriental'),
  array('idDistrito' => '30102','idCanton' => '301','nombreDistrito' => 'Occidental'),
  array('idDistrito' => '30103','idCanton' => '301','nombreDistrito' => 'Carmen'),
  array('idDistrito' => '30104','idCanton' => '301','nombreDistrito' => 'San Nicolás'),
  array('idDistrito' => '30105','idCanton' => '301','nombreDistrito' => 'Aguacaliente o San Francisco'),
  array('idDistrito' => '30106','idCanton' => '301','nombreDistrito' => 'Guadalupe o Arenilla'),
  array('idDistrito' => '30107','idCanton' => '301','nombreDistrito' => 'Corralillo'),
  array('idDistrito' => '30108','idCanton' => '301','nombreDistrito' => 'Tierra Blanca'),
  array('idDistrito' => '30109','idCanton' => '301','nombreDistrito' => 'Dulce Nombre'),
  array('idDistrito' => '30110','idCanton' => '301','nombreDistrito' => 'Llano Grande'),
  array('idDistrito' => '30111','idCanton' => '301','nombreDistrito' => 'Quebradilla'),
  array('idDistrito' => '30201','idCanton' => '302','nombreDistrito' => 'Paraíso'),
  array('idDistrito' => '30202','idCanton' => '302','nombreDistrito' => 'Santiago'),
  array('idDistrito' => '30203','idCanton' => '302','nombreDistrito' => 'Orosi'),
  array('idDistrito' => '30204','idCanton' => '302','nombreDistrito' => 'Cachí'),
  array('idDistrito' => '30205','idCanton' => '302','nombreDistrito' => 'Los Llanos de Santa Lucía'),
  array('idDistrito' => '30301','idCanton' => '303','nombreDistrito' => 'Tres Ríos'),
  array('idDistrito' => '30302','idCanton' => '303','nombreDistrito' => 'San Diego'),
  array('idDistrito' => '30303','idCanton' => '303','nombreDistrito' => 'San Juan'),
  array('idDistrito' => '30304','idCanton' => '303','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '30305','idCanton' => '303','nombreDistrito' => 'Concepción'),
  array('idDistrito' => '30306','idCanton' => '303','nombreDistrito' => 'Dulce Nombre'),
  array('idDistrito' => '30307','idCanton' => '303','nombreDistrito' => 'San Ramón'),
  array('idDistrito' => '30308','idCanton' => '303','nombreDistrito' => 'Río Azul'),
  array('idDistrito' => '30401','idCanton' => '304','nombreDistrito' => 'Juan Viñas'),
  array('idDistrito' => '30402','idCanton' => '304','nombreDistrito' => 'Tucurrique'),
  array('idDistrito' => '30403','idCanton' => '304','nombreDistrito' => 'Pejibaye'),
  array('idDistrito' => '30501','idCanton' => '305','nombreDistrito' => 'Turrialba'),
  array('idDistrito' => '30502','idCanton' => '305','nombreDistrito' => 'La Suiza'),
  array('idDistrito' => '30503','idCanton' => '305','nombreDistrito' => 'Peralta'),
  array('idDistrito' => '30504','idCanton' => '305','nombreDistrito' => 'Santa Cruz'),
  array('idDistrito' => '30505','idCanton' => '305','nombreDistrito' => 'Santa Teresita'),
  array('idDistrito' => '30506','idCanton' => '305','nombreDistrito' => 'Pavones'),
  array('idDistrito' => '30507','idCanton' => '305','nombreDistrito' => 'Tuis'),
  array('idDistrito' => '30508','idCanton' => '305','nombreDistrito' => 'Tayutic'),
  array('idDistrito' => '30509','idCanton' => '305','nombreDistrito' => 'Santa Rosa'),
  array('idDistrito' => '30510','idCanton' => '305','nombreDistrito' => 'Tres Equis'),
  array('idDistrito' => '30511','idCanton' => '305','nombreDistrito' => 'La Isabel'),
  array('idDistrito' => '30512','idCanton' => '305','nombreDistrito' => 'Chirripó'),
  array('idDistrito' => '30601','idCanton' => '306','nombreDistrito' => 'Pacayas'),
  array('idDistrito' => '30602','idCanton' => '306','nombreDistrito' => 'Cervantes'),
  array('idDistrito' => '30603','idCanton' => '306','nombreDistrito' => 'Capellades'),
  array('idDistrito' => '30701','idCanton' => '307','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '30702','idCanton' => '307','nombreDistrito' => 'Cot'),
  array('idDistrito' => '30703','idCanton' => '307','nombreDistrito' => 'Potrero Cerrado'),
  array('idDistrito' => '30704','idCanton' => '307','nombreDistrito' => 'Cipreses'),
  array('idDistrito' => '30705','idCanton' => '307','nombreDistrito' => 'Santa Rosa'),
  array('idDistrito' => '30801','idCanton' => '308','nombreDistrito' => 'El Tejar'),
  array('idDistrito' => '30802','idCanton' => '308','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '30803','idCanton' => '308','nombreDistrito' => 'Tobosi'),
  array('idDistrito' => '30804','idCanton' => '308','nombreDistrito' => 'Patio de Agua'),
  array('idDistrito' => '40101','idCanton' => '401','nombreDistrito' => 'Heredia'),
  array('idDistrito' => '40102','idCanton' => '401','nombreDistrito' => 'Mercedes'),
  array('idDistrito' => '40103','idCanton' => '401','nombreDistrito' => 'San Francisco'),
  array('idDistrito' => '40104','idCanton' => '401','nombreDistrito' => 'Ulloa'),
  array('idDistrito' => '40105','idCanton' => '401','nombreDistrito' => 'Varablanca'),
  array('idDistrito' => '40201','idCanton' => '402','nombreDistrito' => 'Barva'),
  array('idDistrito' => '40202','idCanton' => '402','nombreDistrito' => 'San Pedro'),
  array('idDistrito' => '40203','idCanton' => '402','nombreDistrito' => 'San Pablo'),
  array('idDistrito' => '40204','idCanton' => '402','nombreDistrito' => 'San Roque'),
  array('idDistrito' => '40205','idCanton' => '402','nombreDistrito' => 'Santa Lucía'),
  array('idDistrito' => '40206','idCanton' => '402','nombreDistrito' => 'San José de la Montaña'),
  array('idDistrito' => '40301','idCanton' => '403','nombreDistrito' => 'Santo Domingo'),
  array('idDistrito' => '40302','idCanton' => '403','nombreDistrito' => 'San Vicente'),
  array('idDistrito' => '40303','idCanton' => '403','nombreDistrito' => 'San Miguel'),
  array('idDistrito' => '40304','idCanton' => '403','nombreDistrito' => 'Paracito'),
  array('idDistrito' => '40305','idCanton' => '403','nombreDistrito' => 'Santo Tomás'),
  array('idDistrito' => '40306','idCanton' => '403','nombreDistrito' => 'Santa Rosa'),
  array('idDistrito' => '40307','idCanton' => '403','nombreDistrito' => 'Tures'),
  array('idDistrito' => '40308','idCanton' => '403','nombreDistrito' => 'Pará'),
  array('idDistrito' => '40401','idCanton' => '404','nombreDistrito' => 'Santa Bárbara'),
  array('idDistrito' => '40402','idCanton' => '404','nombreDistrito' => 'San Pedro'),
  array('idDistrito' => '40403','idCanton' => '404','nombreDistrito' => 'San Juan'),
  array('idDistrito' => '40404','idCanton' => '404','nombreDistrito' => 'Jesús'),
  array('idDistrito' => '40405','idCanton' => '404','nombreDistrito' => 'Santo Domingo del Roble'),
  array('idDistrito' => '40406','idCanton' => '404','nombreDistrito' => 'Puraba'),
  array('idDistrito' => '40501','idCanton' => '405','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '40502','idCanton' => '405','nombreDistrito' => 'San Josecito'),
  array('idDistrito' => '40503','idCanton' => '405','nombreDistrito' => 'Santiago'),
  array('idDistrito' => '40504','idCanton' => '405','nombreDistrito' => 'Angeles'),
  array('idDistrito' => '40505','idCanton' => '405','nombreDistrito' => 'Concepción'),
  array('idDistrito' => '40601','idCanton' => '406','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '40602','idCanton' => '406','nombreDistrito' => 'San José'),
  array('idDistrito' => '40603','idCanton' => '406','nombreDistrito' => 'Concepción'),
  array('idDistrito' => '40604','idCanton' => '406','nombreDistrito' => 'San Francisco'),
  array('idDistrito' => '40701','idCanton' => '407','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '40702','idCanton' => '407','nombreDistrito' => 'La Ribera'),
  array('idDistrito' => '40703','idCanton' => '407','nombreDistrito' => 'Asunción'),
  array('idDistrito' => '40801','idCanton' => '408','nombreDistrito' => 'San Joaquín'),
  array('idDistrito' => '40802','idCanton' => '408','nombreDistrito' => 'Barrantes'),
  array('idDistrito' => '40803','idCanton' => '408','nombreDistrito' => 'Llorente'),
  array('idDistrito' => '40901','idCanton' => '409','nombreDistrito' => 'San Pablo'),
  array('idDistrito' => '41001','idCanton' => '410','nombreDistrito' => 'Puerto Viejo'),
  array('idDistrito' => '41002','idCanton' => '410','nombreDistrito' => 'La Virgen'),
  array('idDistrito' => '41003','idCanton' => '410','nombreDistrito' => 'Horquetas'),
  array('idDistrito' => '41004','idCanton' => '410','nombreDistrito' => 'Llanuras de Gaspar'),
  array('idDistrito' => '41005','idCanton' => '410','nombreDistrito' => 'Cureña'),
  array('idDistrito' => '50101','idCanton' => '501','nombreDistrito' => 'Liberia'),
  array('idDistrito' => '50102','idCanton' => '501','nombreDistrito' => 'Cañas Dulces'),
  array('idDistrito' => '50103','idCanton' => '501','nombreDistrito' => 'Mayorga'),
  array('idDistrito' => '50104','idCanton' => '501','nombreDistrito' => 'Nacascolo'),
  array('idDistrito' => '50105','idCanton' => '501','nombreDistrito' => 'Curubande'),
  array('idDistrito' => '50201','idCanton' => '502','nombreDistrito' => 'Nicoya'),
  array('idDistrito' => '50202','idCanton' => '502','nombreDistrito' => 'Mansión'),
  array('idDistrito' => '50203','idCanton' => '502','nombreDistrito' => 'San Antonio'),
  array('idDistrito' => '50204','idCanton' => '502','nombreDistrito' => 'Quebrada Honda'),
  array('idDistrito' => '50205','idCanton' => '502','nombreDistrito' => 'Sámara'),
  array('idDistrito' => '50206','idCanton' => '502','nombreDistrito' => 'Nósara'),
  array('idDistrito' => '50207','idCanton' => '502','nombreDistrito' => 'Belén de Nosarita'),
  array('idDistrito' => '50301','idCanton' => '503','nombreDistrito' => 'Santa Cruz'),
  array('idDistrito' => '50302','idCanton' => '503','nombreDistrito' => 'Bolsón'),
  array('idDistrito' => '50303','idCanton' => '503','nombreDistrito' => 'Veintisiete de Abril'),
  array('idDistrito' => '50304','idCanton' => '503','nombreDistrito' => 'Tempate'),
  array('idDistrito' => '50305','idCanton' => '503','nombreDistrito' => 'Cartagena'),
  array('idDistrito' => '50306','idCanton' => '503','nombreDistrito' => 'Cuajiniquil'),
  array('idDistrito' => '50307','idCanton' => '503','nombreDistrito' => 'Diriá'),
  array('idDistrito' => '50308','idCanton' => '503','nombreDistrito' => 'Cabo Velas'),
  array('idDistrito' => '50309','idCanton' => '503','nombreDistrito' => 'Tamarindo'),
  array('idDistrito' => '50401','idCanton' => '504','nombreDistrito' => 'Bagaces'),
  array('idDistrito' => '50402','idCanton' => '504','nombreDistrito' => 'Fortuna'),
  array('idDistrito' => '50403','idCanton' => '504','nombreDistrito' => 'Mogote'),
  array('idDistrito' => '50404','idCanton' => '504','nombreDistrito' => 'Río Naranjo'),
  array('idDistrito' => '50501','idCanton' => '505','nombreDistrito' => 'Filadelfia'),
  array('idDistrito' => '50502','idCanton' => '505','nombreDistrito' => 'Palmira'),
  array('idDistrito' => '50503','idCanton' => '505','nombreDistrito' => 'Sardinal'),
  array('idDistrito' => '50504','idCanton' => '505','nombreDistrito' => 'Belén'),
  array('idDistrito' => '50601','idCanton' => '506','nombreDistrito' => 'Cañas'),
  array('idDistrito' => '50602','idCanton' => '506','nombreDistrito' => 'Palmira'),
  array('idDistrito' => '50603','idCanton' => '506','nombreDistrito' => 'San Miguel'),
  array('idDistrito' => '50604','idCanton' => '506','nombreDistrito' => 'Bebedero'),
  array('idDistrito' => '50605','idCanton' => '506','nombreDistrito' => 'Porozal'),
  array('idDistrito' => '50701','idCanton' => '507','nombreDistrito' => 'Juntas'),
  array('idDistrito' => '50702','idCanton' => '507','nombreDistrito' => 'Sierra'),
  array('idDistrito' => '50703','idCanton' => '507','nombreDistrito' => 'San Juan'),
  array('idDistrito' => '50704','idCanton' => '507','nombreDistrito' => 'Colorado'),
  array('idDistrito' => '50801','idCanton' => '508','nombreDistrito' => 'Tilarán'),
  array('idDistrito' => '50802','idCanton' => '508','nombreDistrito' => 'Quebrada Grande'),
  array('idDistrito' => '50803','idCanton' => '508','nombreDistrito' => 'Tronadora'),
  array('idDistrito' => '50804','idCanton' => '508','nombreDistrito' => 'Santa Rosa'),
  array('idDistrito' => '50805','idCanton' => '508','nombreDistrito' => 'Líbano'),
  array('idDistrito' => '50806','idCanton' => '508','nombreDistrito' => 'Tierras Morenas'),
  array('idDistrito' => '50807','idCanton' => '508','nombreDistrito' => 'Arenal'),
  array('idDistrito' => '50901','idCanton' => '509','nombreDistrito' => 'Carmona'),
  array('idDistrito' => '50902','idCanton' => '509','nombreDistrito' => 'Santa Rita'),
  array('idDistrito' => '50903','idCanton' => '509','nombreDistrito' => 'Zapotal'),
  array('idDistrito' => '50904','idCanton' => '509','nombreDistrito' => 'San Pablo'),
  array('idDistrito' => '50905','idCanton' => '509','nombreDistrito' => 'Porvenir'),
  array('idDistrito' => '50906','idCanton' => '509','nombreDistrito' => 'Bejuco'),
  array('idDistrito' => '51001','idCanton' => '510','nombreDistrito' => 'La Cruz'),
  array('idDistrito' => '51002','idCanton' => '510','nombreDistrito' => 'Santa Cecilia'),
  array('idDistrito' => '51003','idCanton' => '510','nombreDistrito' => 'Garita'),
  array('idDistrito' => '51004','idCanton' => '510','nombreDistrito' => 'Santa Elena'),
  array('idDistrito' => '51101','idCanton' => '511','nombreDistrito' => 'Hojancha'),
  array('idDistrito' => '51102','idCanton' => '511','nombreDistrito' => 'Monte Romo'),
  array('idDistrito' => '51103','idCanton' => '511','nombreDistrito' => 'Puerto Carrillo'),
  array('idDistrito' => '51104','idCanton' => '511','nombreDistrito' => 'Huacas'),
  array('idDistrito' => '60101','idCanton' => '601','nombreDistrito' => 'Puntarenas'),
  array('idDistrito' => '60102','idCanton' => '601','nombreDistrito' => 'Pitahaya'),
  array('idDistrito' => '60103','idCanton' => '601','nombreDistrito' => 'Chomes'),
  array('idDistrito' => '60104','idCanton' => '601','nombreDistrito' => 'Lepanto'),
  array('idDistrito' => '60105','idCanton' => '601','nombreDistrito' => 'Paquera'),
  array('idDistrito' => '60106','idCanton' => '601','nombreDistrito' => 'Manzanillo'),
  array('idDistrito' => '60107','idCanton' => '601','nombreDistrito' => 'Guacimal'),
  array('idDistrito' => '60108','idCanton' => '601','nombreDistrito' => 'Barranca'),
  array('idDistrito' => '60109','idCanton' => '601','nombreDistrito' => 'Monte Verde'),
  array('idDistrito' => '60110','idCanton' => '601','nombreDistrito' => 'Isla del Coco'),
  array('idDistrito' => '60111','idCanton' => '601','nombreDistrito' => 'Cóbano'),
  array('idDistrito' => '60112','idCanton' => '601','nombreDistrito' => 'Chacarita'),
  array('idDistrito' => '60113','idCanton' => '601','nombreDistrito' => 'Chira'),
  array('idDistrito' => '60114','idCanton' => '601','nombreDistrito' => 'Acapulco'),
  array('idDistrito' => '60115','idCanton' => '601','nombreDistrito' => 'Roble'),
  array('idDistrito' => '60116','idCanton' => '601','nombreDistrito' => 'Arancibia'),
  array('idDistrito' => '60201','idCanton' => '602','nombreDistrito' => 'Espíritu Santo'),
  array('idDistrito' => '60202','idCanton' => '602','nombreDistrito' => 'San Juan Grande'),
  array('idDistrito' => '60203','idCanton' => '602','nombreDistrito' => 'Macacona'),
  array('idDistrito' => '60204','idCanton' => '602','nombreDistrito' => 'San Rafael'),
  array('idDistrito' => '60205','idCanton' => '602','nombreDistrito' => 'San Jerónimo'),
  array('idDistrito' => '60301','idCanton' => '603','nombreDistrito' => 'Buenos Aires'),
  array('idDistrito' => '60302','idCanton' => '603','nombreDistrito' => 'Volcán'),
  array('idDistrito' => '60303','idCanton' => '603','nombreDistrito' => 'Potrero Grande'),
  array('idDistrito' => '60304','idCanton' => '603','nombreDistrito' => 'Boruca'),
  array('idDistrito' => '60305','idCanton' => '603','nombreDistrito' => 'Pilas'),
  array('idDistrito' => '60306','idCanton' => '603','nombreDistrito' => 'Colinas o Bajo de Maíz'),
  array('idDistrito' => '60307','idCanton' => '603','nombreDistrito' => 'Chánguena'),
  array('idDistrito' => '60308','idCanton' => '603','nombreDistrito' => 'Bioley'),
  array('idDistrito' => '60309','idCanton' => '603','nombreDistrito' => 'Brunka'),
  array('idDistrito' => '60401','idCanton' => '604','nombreDistrito' => 'Miramar'),
  array('idDistrito' => '60402','idCanton' => '604','nombreDistrito' => 'Unión'),
  array('idDistrito' => '60403','idCanton' => '604','nombreDistrito' => 'San Isidro'),
  array('idDistrito' => '60501','idCanton' => '605','nombreDistrito' => 'Puerto Cortés'),
  array('idDistrito' => '60502','idCanton' => '605','nombreDistrito' => 'Palmar'),
  array('idDistrito' => '60503','idCanton' => '605','nombreDistrito' => 'Sierpe'),
  array('idDistrito' => '60504','idCanton' => '605','nombreDistrito' => 'Bahía Ballena'),
  array('idDistrito' => '60505','idCanton' => '605','nombreDistrito' => 'Piedras Blancas'),
  array('idDistrito' => '60601','idCanton' => '606','nombreDistrito' => 'Quepos'),
  array('idDistrito' => '60602','idCanton' => '606','nombreDistrito' => 'Savegre'),
  array('idDistrito' => '60603','idCanton' => '606','nombreDistrito' => 'Naranjito'),
  array('idDistrito' => '60701','idCanton' => '607','nombreDistrito' => 'Golfito'),
  array('idDistrito' => '60702','idCanton' => '607','nombreDistrito' => 'Puerto Jiménez'),
  array('idDistrito' => '60703','idCanton' => '607','nombreDistrito' => 'Guaycará'),
  array('idDistrito' => '60704','idCanton' => '607','nombreDistrito' => 'Pavon'),
  array('idDistrito' => '60801','idCanton' => '608','nombreDistrito' => 'San Vito'),
  array('idDistrito' => '60802','idCanton' => '608','nombreDistrito' => 'Sabalito'),
  array('idDistrito' => '60803','idCanton' => '608','nombreDistrito' => 'Agua Buena'),
  array('idDistrito' => '60804','idCanton' => '608','nombreDistrito' => 'Limoncito'),
  array('idDistrito' => '60805','idCanton' => '608','nombreDistrito' => 'Pittier'),
  array('idDistrito' => '60901','idCanton' => '609','nombreDistrito' => 'Parrita'),
  array('idDistrito' => '61001','idCanton' => '610','nombreDistrito' => 'Corredor'),
  array('idDistrito' => '61002','idCanton' => '610','nombreDistrito' => 'La Cuesta'),
  array('idDistrito' => '61003','idCanton' => '610','nombreDistrito' => 'Paso Canoas'),
  array('idDistrito' => '61004','idCanton' => '610','nombreDistrito' => 'Laurel'),
  array('idDistrito' => '61101','idCanton' => '611','nombreDistrito' => 'Jacó'),
  array('idDistrito' => '61102','idCanton' => '611','nombreDistrito' => 'Tárcoles'),
  array('idDistrito' => '70101','idCanton' => '701','nombreDistrito' => 'Limón'),
  array('idDistrito' => '70102','idCanton' => '701','nombreDistrito' => 'Valle La Estrella'),
  array('idDistrito' => '70103','idCanton' => '701','nombreDistrito' => 'Río Blanco'),
  array('idDistrito' => '70104','idCanton' => '701','nombreDistrito' => 'Matama'),
  array('idDistrito' => '70201','idCanton' => '702','nombreDistrito' => 'Guápiles'),
  array('idDistrito' => '70202','idCanton' => '702','nombreDistrito' => 'Jiménez'),
  array('idDistrito' => '70203','idCanton' => '702','nombreDistrito' => 'Rita'),
  array('idDistrito' => '70204','idCanton' => '702','nombreDistrito' => 'Roxana'),
  array('idDistrito' => '70205','idCanton' => '702','nombreDistrito' => 'Cariari'),
  array('idDistrito' => '70206','idCanton' => '702','nombreDistrito' => 'Colorado'),
  array('idDistrito' => '70301','idCanton' => '703','nombreDistrito' => 'Siquirres'),
  array('idDistrito' => '70302','idCanton' => '703','nombreDistrito' => 'Pacuarito'),
  array('idDistrito' => '70303','idCanton' => '703','nombreDistrito' => 'Florida'),
  array('idDistrito' => '70304','idCanton' => '703','nombreDistrito' => 'Germania'),
  array('idDistrito' => '70305','idCanton' => '703','nombreDistrito' => 'Cairo'),
  array('idDistrito' => '70306','idCanton' => '703','nombreDistrito' => 'Alegría'),
  array('idDistrito' => '70401','idCanton' => '704','nombreDistrito' => 'Bratsi'),
  array('idDistrito' => '70402','idCanton' => '704','nombreDistrito' => 'Sixaola'),
  array('idDistrito' => '70403','idCanton' => '704','nombreDistrito' => 'Cahuita'),
  array('idDistrito' => '70404','idCanton' => '704','nombreDistrito' => 'Telire'),
  array('idDistrito' => '70501','idCanton' => '705','nombreDistrito' => 'Matina'),
  array('idDistrito' => '70502','idCanton' => '705','nombreDistrito' => 'Batán'),
  array('idDistrito' => '70503','idCanton' => '705','nombreDistrito' => 'Carrandí'),
  array('idDistrito' => '70601','idCanton' => '706','nombreDistrito' => 'Guácimo'),
  array('idDistrito' => '70602','idCanton' => '706','nombreDistrito' => 'Mercedes'),
  array('idDistrito' => '70603','idCanton' => '706','nombreDistrito' => 'Pocora'),
  array('idDistrito' => '70604','idCanton' => '706','nombreDistrito' => 'Río Jiménez'),
  array('idDistrito' => '70605','idCanton' => '706','nombreDistrito' => 'Duacarí')
);

// `gymrug`.`Provincias`
$Provincias = array(
  array('idProvincia' => '1','nombreProvincia' => 'San José'),
  array('idProvincia' => '2','nombreProvincia' => 'Alajuela'),
  array('idProvincia' => '3','nombreProvincia' => 'Heredia'),
  array('idProvincia' => '4','nombreProvincia' => 'Cartago'),
  array('idProvincia' => '5','nombreProvincia' => 'Puntarenas'),
  array('idProvincia' => '6','nombreProvincia' => 'Guanacaste'),
  array('idProvincia' => '7','nombreProvincia' => 'Limón')
);
